import fs from 'fs'
import path from 'path'

/**
 * Shared model folders — reuse an existing ComfyUI install's models instead of
 * downloading everything twice.
 *
 * ComfyUI already solves this natively: on startup it loads
 * `<ComfyUI>/extra_model_paths.yaml` and registers every folder listed there as
 * an extra search path, so the models show up in `/object_info` (and therefore
 * in every dropdown and the Models page's installed check) with no app-side
 * merging. All we do is generate that file from the Settings field.
 */

const MARKER = '# Generated by Raccoon Studio'
const FILENAME = 'extra_model_paths.yaml'

/**
 * ComfyUI folder keys whose on-disk directory name differs from the key nodes
 * look models up under. Everything else (checkpoints, loras, vae, controlnet,
 * upscale_models, embeddings, …) is named after its directory.
 */
const ALIASES: Record<string, string> = {
  unet: 'diffusion_models',
  clip: 'text_encoders',
  t2i_adapter: 'controlnet',
}

const isDir = (p: string): boolean => {
  try { return fs.statSync(p).isDirectory() } catch { return false }
}

/** Accept either a ComfyUI install root or its `models/` folder directly. */
export function resolveSharedModelsDir(dir: string): string {
  const models = path.join(dir, 'models')
  return isDir(models) ? models : dir
}

/**
 * One `raccoon_shared:` block: an absolute `base_path` plus one entry per
 * subfolder. Sub-paths use block scalars so several directories can collapse
 * onto one key (`unet` + `diffusion_models`) and need no quoting.
 */
export function buildExtraModelPathsYaml(baseDir: string, subdirs: string[]): string {
  const byKey = new Map<string, string[]>()
  for (const name of [...subdirs].sort()) {
    const key = ALIASES[name] ?? name
    byKey.set(key, [...(byKey.get(key) ?? []), name])
  }
  const lines = [
    `${MARKER} — change it from Settings, not by hand (it gets overwritten).`,
    'raccoon_shared:',
    `  base_path: '${baseDir.replace(/'/g, "''")}'`,
  ]
  for (const [key, dirs] of byKey) lines.push(`  ${key}: |`, ...dirs.map((d) => `    ${d}`))
  return lines.join('\n') + '\n'
}

/**
 * Writes (or, for an empty `sharedDir`, removes) the generated config in
 * `comfyDir`. Refuses to clobber a hand-written `extra_model_paths.yaml` —
 * someone with one of those has their own sharing setup already.
 * Takes effect on the next ComfyUI start.
 */
export function syncExtraModelPaths(comfyDir: string, sharedDir: string): void {
  const file = path.join(comfyDir, FILENAME)
  const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : ''
  const ours = existing.startsWith(MARKER)

  if (!sharedDir) {
    if (ours) fs.rmSync(file)
    return
  }
  if (existing && !ours) {
    throw new Error(`${file} already exists and was not written by Raccoon Studio — edit it by hand instead.`)
  }

  const base = resolveSharedModelsDir(sharedDir)
  if (!isDir(base)) throw new Error(`Not a folder: ${base}`)
  const subdirs = fs.readdirSync(base, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !e.name.startsWith('.') && e.name !== '__pycache__')
    .map((e) => e.name)
  if (subdirs.length === 0) throw new Error(`${base} has no model subfolders — point at a ComfyUI install or its models folder.`)

  fs.writeFileSync(file, buildExtraModelPathsYaml(base, subdirs), 'utf8')
}
