export type PromptMode = 'photoreal' | 'anime'

export interface TemplateOption { id: string; label: string; fragment: string }
export interface TemplateCategory { id: string; label: string; options: TemplateOption[] }

const CATEGORY_ORDER = [
  'subject', 'bodytype', 'complexion', 'hair', 'clothing', 'womensclothing',
  'underwear', 'bikinis', 'accessories', 'location', 'timeweather', 'pose',
  'expression', 'lighting', 'camera', 'composition', 'color', 'artstyle',
  'mood', 'quality',
] as const

export const TEMPLATES: Record<PromptMode, TemplateCategory[]> = {
  photoreal: [
    { id: 'subject', label: 'Subject / person', options: [
      { id: 'woman-20s', label: 'Woman, 20s', fragment: 'a young woman in her 20s' },
      { id: 'woman-30s', label: 'Woman, 30s', fragment: 'a woman in her 30s' },
      { id: 'woman-40s', label: 'Woman, 40s', fragment: 'a woman in her 40s' },
      { id: 'woman-50s', label: 'Woman, 50s', fragment: 'a woman in her 50s' },
      { id: 'man-20s', label: 'Man, 20s', fragment: 'a young man in his 20s' },
      { id: 'man-30s', label: 'Man, 30s', fragment: 'a man in his 30s' },
      { id: 'man-40s', label: 'Man, 40s', fragment: 'a man in his 40s' },
      { id: 'man-50s', label: 'Man, 50s', fragment: 'a man in his 50s' },
      { id: 'elderly-woman', label: 'Elderly woman', fragment: 'an elderly woman with gentle features' },
      { id: 'elderly-man', label: 'Elderly man', fragment: 'an elderly man with weathered features' },
      { id: 'teen-girl', label: 'Teen girl', fragment: 'a teenage girl' },
      { id: 'teen-boy', label: 'Teen boy', fragment: 'a teenage boy' },
      { id: 'child', label: 'Child', fragment: 'a young child' },
      { id: 'couple', label: 'Couple', fragment: 'a couple together' },
      { id: 'athlete', label: 'Athlete', fragment: 'an athletic person with a toned physique' },
      { id: 'businesswoman', label: 'Businesswoman', fragment: 'a poised businesswoman' },
      { id: 'businessman', label: 'Businessman', fragment: 'a sharp businessman' },
      { id: 'model-f', label: 'Female model', fragment: 'a striking female fashion model' },
      { id: 'model-m', label: 'Male model', fragment: 'a striking male fashion model' },
      { id: 'dancer', label: 'Dancer', fragment: 'a graceful dancer' },
      { id: 'soldier', label: 'Soldier', fragment: 'a rugged soldier' },
    ]},
    { id: 'bodytype', label: 'Body type', options: [
      { id: 'slim', label: 'Slim', fragment: 'with a slim slender build' },
      { id: 'athletic', label: 'Athletic', fragment: 'with an athletic toned build' },
      { id: 'curvy', label: 'Curvy', fragment: 'with a curvy hourglass figure' },
      { id: 'petite', label: 'Petite', fragment: 'with a petite small frame' },
      { id: 'average', label: 'Average', fragment: 'with an average build' },
      { id: 'plus-size', label: 'Plus-size', fragment: 'with a plus-size full figure' },
      { id: 'muscular', label: 'Muscular', fragment: 'with a muscular build' },
      { id: 'tall', label: 'Tall', fragment: 'with a tall stature' },
      { id: 'broad', label: 'Broad-shouldered', fragment: 'with a broad-shouldered frame' },
      { id: 'stocky', label: 'Stocky', fragment: 'with a stocky, solid build' },
      { id: 'lean-m', label: 'Lean (m)', fragment: 'with a lean, defined male physique' },
      { id: 'muscular-m', label: 'Bodybuilder (m)', fragment: 'with a heavily muscled male bodybuilder physique' },
      { id: 'fitness-model', label: 'Fitness model (f)', fragment: 'with a lean female fitness-model physique and defined abs' },
      { id: 'toned-muscular-f', label: 'Toned muscular (f)', fragment: 'with a toned, athletic muscular female physique' },
      { id: 'female-bodybuilder', label: 'Bodybuilder (f)', fragment: 'with a muscular female bodybuilder physique, well-developed muscles' },
      { id: 'shredded-f', label: 'Shredded (f)', fragment: 'with a shredded, highly defined muscular female physique' },
      { id: 'competition-f', label: 'Competition pro (f)', fragment: 'with a competition-ready female bodybuilder physique, deep muscle separation and definition' },
      { id: 'powerlifter-f', label: 'Powerlifter (f)', fragment: 'with a powerful, thick-muscled female powerlifter build' },
      { id: 'amazon-f', label: 'Amazonian (f)', fragment: 'with a tall, powerful amazonian muscular female build' },
      { id: 'vascular-f', label: 'Vascular (f)', fragment: 'with a hard, vascular muscular female physique' },
      { id: 'slender-tall', label: 'Tall & slender', fragment: 'with a tall, slender frame' },
    ]},
    { id: 'complexion', label: 'Skin tone', options: [
      { id: 'fair', label: 'Fair', fragment: 'fair porcelain skin' },
      { id: 'light', label: 'Light', fragment: 'a light complexion' },
      { id: 'rosy', label: 'Rosy', fragment: 'rosy fair skin' },
      { id: 'pale', label: 'Pale', fragment: 'pale skin' },
      { id: 'freckled', label: 'Freckled', fragment: 'freckled skin' },
      { id: 'warm-beige', label: 'Warm beige', fragment: 'warm beige skin' },
      { id: 'olive', label: 'Olive', fragment: 'olive skin' },
      { id: 'sun-kissed', label: 'Sun-kissed', fragment: 'sun-kissed skin' },
      { id: 'tan', label: 'Tan', fragment: 'tanned skin' },
      { id: 'golden', label: 'Golden', fragment: 'golden-toned skin' },
      { id: 'bronze', label: 'Bronze', fragment: 'bronze skin' },
      { id: 'caramel', label: 'Caramel', fragment: 'caramel skin' },
      { id: 'honey', label: 'Honey', fragment: 'warm honey skin' },
      { id: 'mocha', label: 'Mocha', fragment: 'mocha skin' },
      { id: 'deep-brown', label: 'Deep brown', fragment: 'deep brown skin' },
      { id: 'dark', label: 'Dark', fragment: 'dark skin' },
      { id: 'ebony', label: 'Ebony', fragment: 'rich ebony skin' },
      { id: 'cool-undertone', label: 'Cool undertone', fragment: 'skin with cool undertones' },
      { id: 'warm-undertone', label: 'Warm undertone', fragment: 'skin with warm undertones' },
      { id: 'weathered', label: 'Weathered', fragment: 'weathered sun-aged skin' },
      { id: 'flawless', label: 'Flawless', fragment: 'a flawless smooth complexion' },
    ]},
    { id: 'hair', label: 'Hair', options: [
      { id: 'long-black', label: 'Long black', fragment: 'long flowing black hair' },
      { id: 'long-blonde', label: 'Long blonde', fragment: 'long wavy blonde hair' },
      { id: 'short-brown', label: 'Short brown', fragment: 'short tidy brown hair' },
      { id: 'red-curly', label: 'Red curly', fragment: 'curly red hair' },
      { id: 'buzz', label: 'Buzz cut', fragment: 'a closely cropped buzz cut' },
      { id: 'bald', label: 'Bald', fragment: 'a clean-shaven bald head' },
      { id: 'ponytail', label: 'Ponytail', fragment: 'hair tied back in a ponytail' },
      { id: 'messy-bun', label: 'Messy bun', fragment: 'hair in a loose messy bun' },
      { id: 'silver-gray', label: 'Silver gray', fragment: 'silver-gray hair' },
      { id: 'braided', label: 'Braided', fragment: 'intricately braided hair' },
      { id: 'bob', label: 'Bob', fragment: 'a sleek bob cut' },
      { id: 'pixie', label: 'Pixie', fragment: 'a short pixie cut' },
      { id: 'wavy-brunette', label: 'Wavy brunette', fragment: 'shoulder-length wavy brunette hair' },
      { id: 'long-straight', label: 'Long straight', fragment: 'long straight hair' },
      { id: 'afro', label: 'Afro', fragment: 'a voluminous afro' },
      { id: 'dreadlocks', label: 'Dreadlocks', fragment: 'long dreadlocks' },
      { id: 'cornrows', label: 'Cornrows', fragment: 'neat cornrows' },
      { id: 'undercut', label: 'Undercut', fragment: 'a stylish undercut' },
      { id: 'man-bun', label: 'Man bun', fragment: 'hair in a man bun' },
      { id: 'wavy-blonde', label: 'Wavy blonde', fragment: 'wavy blonde shoulder-length hair' },
      { id: 'dyed-vibrant', label: 'Dyed vibrant', fragment: 'vibrantly dyed colored hair' },
      { id: 'slicked-back', label: 'Slicked back', fragment: 'slicked-back hair' },
    ]},
    { id: 'clothing', label: 'Clothing', options: [
      { id: 'business', label: 'Business suit', fragment: 'wearing a tailored business suit' },
      { id: 'casual', label: 'Streetwear', fragment: 'wearing casual streetwear' },
      { id: 'leather-jacket', label: 'Leather jacket', fragment: 'wearing a worn leather jacket' },
      { id: 'hoodie-jeans', label: 'Hoodie & jeans', fragment: 'wearing a hoodie and jeans' },
      { id: 'traditional', label: 'Traditional attire', fragment: 'wearing traditional cultural attire' },
      { id: 'winter-coat', label: 'Winter coat', fragment: 'bundled in a heavy winter coat' },
      { id: 'uniform', label: 'Work uniform', fragment: 'wearing a work uniform' },
      { id: 'sportswear', label: 'Sportswear', fragment: 'wearing athletic sportswear' },
      { id: 'trench', label: 'Trench coat', fragment: 'wearing a classic trench coat' },
      { id: 'tshirt-jeans', label: 'T-shirt & jeans', fragment: 'wearing a plain t-shirt and jeans' },
      { id: 'tuxedo', label: 'Tuxedo', fragment: 'wearing a sharp tuxedo' },
      { id: 'denim-jacket', label: 'Denim jacket', fragment: 'wearing a denim jacket' },
      { id: 'flannel', label: 'Flannel shirt', fragment: 'wearing a flannel shirt' },
      { id: 'turtleneck', label: 'Turtleneck', fragment: 'wearing a cozy turtleneck sweater' },
      { id: 'raincoat', label: 'Raincoat', fragment: 'wearing a yellow raincoat' },
      { id: 'overalls', label: 'Overalls', fragment: 'wearing rugged overalls' },
      { id: 'bomber', label: 'Bomber jacket', fragment: 'wearing a bomber jacket' },
      { id: 'polo-chinos', label: 'Polo & chinos', fragment: 'wearing a polo shirt and chinos' },
      { id: 'puffer', label: 'Puffer jacket', fragment: 'wearing a puffer jacket' },
      { id: 'cardigan', label: 'Cardigan', fragment: 'wearing a knit cardigan' },
      { id: 'waistcoat', label: 'Waistcoat', fragment: 'wearing a dress shirt and waistcoat' },
    ]},
    { id: 'womensclothing', label: "Women's clothing", options: [
      { id: 'evening-gown', label: 'Evening gown', fragment: 'wearing an elegant evening gown' },
      { id: 'cocktail-dress', label: 'Cocktail dress', fragment: 'wearing a chic cocktail dress' },
      { id: 'summer-dress', label: 'Summer dress', fragment: 'wearing a light summer dress' },
      { id: 'sundress', label: 'Sundress', fragment: 'wearing a floral sundress' },
      { id: 'pencil-skirt', label: 'Pencil skirt', fragment: 'wearing a fitted pencil skirt and blouse' },
      { id: 'mini-skirt', label: 'Mini skirt', fragment: 'wearing a mini skirt and top' },
      { id: 'maxi-dress', label: 'Maxi dress', fragment: 'wearing a flowing maxi dress' },
      { id: 'blouse-jeans', label: 'Blouse & jeans', fragment: 'wearing a silk blouse and jeans' },
      { id: 'crop-top', label: 'Crop top', fragment: 'wearing a crop top and high-waisted jeans' },
      { id: 'wrap-dress', label: 'Wrap dress', fragment: 'wearing a wrap dress' },
      { id: 'pleated-skirt', label: 'Pleated skirt', fragment: 'wearing a pleated skirt and blouse' },
      { id: 'bodycon', label: 'Bodycon dress', fragment: 'wearing a bodycon dress' },
      { id: 'jumpsuit', label: 'Jumpsuit', fragment: 'wearing a tailored jumpsuit' },
      { id: 'romper', label: 'Romper', fragment: 'wearing a casual romper' },
      { id: 'sweater-dress', label: 'Sweater dress', fragment: 'wearing a knit sweater dress' },
      { id: 'blazer-skirt', label: 'Blazer & skirt', fragment: 'wearing a blazer and skirt' },
      { id: 'halter-dress', label: 'Halter dress', fragment: 'wearing a halter-neck dress' },
      { id: 'off-shoulder', label: 'Off-shoulder top', fragment: 'wearing an off-shoulder top' },
      { id: 'leggings-top', label: 'Leggings & top', fragment: 'wearing leggings and a fitted top' },
      { id: 'ballgown', label: 'Ballgown', fragment: 'wearing an opulent ballgown' },
      { id: 'leather-skirt', label: 'Leather skirt', fragment: 'wearing a leather skirt and top' },
    ]},
    { id: 'underwear', label: 'Underwear', options: [
      { id: 'lingerie', label: 'Lace lingerie', fragment: 'wearing elegant lace lingerie' },
      { id: 'bra-panties', label: 'Bra & panties', fragment: 'wearing a matching bra and panties set' },
      { id: 'silk-robe', label: 'Silk robe', fragment: 'wearing an open silk robe over lingerie' },
      { id: 'boxers', label: 'Boxers', fragment: 'wearing boxer shorts' },
      { id: 'briefs', label: 'Briefs', fragment: 'wearing fitted briefs' },
      { id: 'boxer-briefs', label: 'Boxer briefs', fragment: 'wearing boxer briefs' },
      { id: 'sports-underwear', label: 'Sports underwear', fragment: 'wearing a sports bra and athletic underwear' },
      { id: 'thong', label: 'Thong', fragment: 'wearing a lace thong' },
      { id: 'boyshorts', label: 'Boyshorts', fragment: 'wearing boyshorts' },
      { id: 'babydoll', label: 'Babydoll', fragment: 'wearing a sheer babydoll' },
      { id: 'teddy', label: 'Teddy', fragment: 'wearing a lace teddy' },
      { id: 'corset', label: 'Corset', fragment: 'wearing a cinched corset' },
      { id: 'bustier', label: 'Bustier', fragment: 'wearing a satin bustier' },
      { id: 'garter', label: 'Garter & stockings', fragment: 'wearing a garter belt and stockings' },
      { id: 'chemise', label: 'Chemise', fragment: 'wearing a silk chemise' },
      { id: 'bodysuit', label: 'Lace bodysuit', fragment: 'wearing a lace bodysuit' },
      { id: 'push-up', label: 'Push-up set', fragment: 'wearing a push-up bra and panties' },
      { id: 'camisole', label: 'Camisole & shorts', fragment: 'wearing a camisole and shorts' },
      { id: 'slip', label: 'Satin slip', fragment: 'wearing a satin slip' },
      { id: 'lace-set', label: 'Lace set', fragment: 'wearing a delicate lace lingerie set' },
      { id: 'strappy-set', label: 'Strappy set', fragment: 'wearing a strappy lingerie set' },
    ]},
    { id: 'bikinis', label: 'Bikinis / swimwear', options: [
      { id: 'string-bikini', label: 'String bikini', fragment: 'wearing a string bikini' },
      { id: 'triangle-bikini', label: 'Triangle bikini', fragment: 'wearing a triangle-top bikini' },
      { id: 'bandeau-bikini', label: 'Bandeau bikini', fragment: 'wearing a strapless bandeau bikini' },
      { id: 'halter-bikini', label: 'Halter bikini', fragment: 'wearing a halter-neck bikini' },
      { id: 'highwaist-bikini', label: 'High-waist bikini', fragment: 'wearing a high-waisted retro bikini' },
      { id: 'sporty-bikini', label: 'Sporty bikini', fragment: 'wearing a sporty athletic bikini' },
      { id: 'micro-bikini', label: 'Micro bikini', fragment: 'wearing a minimal micro bikini' },
      { id: 'monokini', label: 'Monokini', fragment: 'wearing a cut-out monokini' },
      { id: 'one-piece', label: 'One-piece', fragment: 'wearing a sleek one-piece swimsuit' },
      { id: 'thong-bikini', label: 'Thong bikini', fragment: 'wearing a thong bikini' },
      { id: 'sidetie-bikini', label: 'Side-tie bikini', fragment: 'wearing a side-tie bikini' },
      { id: 'tankini', label: 'Tankini', fragment: 'wearing a tankini' },
      { id: 'crochet-bikini', label: 'Crochet bikini', fragment: 'wearing a crochet bikini' },
      { id: 'ruffle-bikini', label: 'Ruffle bikini', fragment: 'wearing a bandeau bikini with ruffles' },
      { id: 'underwire-bikini', label: 'Underwire bikini', fragment: 'wearing an underwire bikini top' },
      { id: 'sling-swimsuit', label: 'Sling swimsuit', fragment: 'wearing a sling one-piece swimsuit' },
      { id: 'ruched-bikini', label: 'Ruched bikini', fragment: 'wearing a ruched bikini' },
      { id: 'wrap-bikini', label: 'Wrap bikini', fragment: 'wearing a wrap-style bikini top' },
      { id: 'floral-bikini', label: 'Floral bikini', fragment: 'wearing a floral print bikini' },
      { id: 'neon-bikini', label: 'Neon bikini', fragment: 'wearing a neon string bikini' },
      { id: 'metallic-bikini', label: 'Metallic bikini', fragment: 'wearing a metallic bikini' },
    ]},
    { id: 'accessories', label: 'Accessories', options: [
      { id: 'none', label: 'None', fragment: '' },
      { id: 'glasses', label: 'Glasses', fragment: 'wearing stylish glasses' },
      { id: 'sunglasses', label: 'Sunglasses', fragment: 'wearing sunglasses' },
      { id: 'sunhat', label: 'Sun hat', fragment: 'wearing a wide-brim sun hat' },
      { id: 'beanie', label: 'Beanie', fragment: 'wearing a knit beanie' },
      { id: 'cap', label: 'Cap', fragment: 'wearing a baseball cap' },
      { id: 'earrings', label: 'Earrings', fragment: 'wearing elegant earrings' },
      { id: 'necklace', label: 'Necklace', fragment: 'wearing a delicate necklace' },
      { id: 'choker', label: 'Choker', fragment: 'wearing a choker' },
      { id: 'statement-jewelry', label: 'Statement jewelry', fragment: 'wearing bold statement jewelry' },
      { id: 'watch', label: 'Watch', fragment: 'wearing a luxury watch' },
      { id: 'scarf', label: 'Scarf', fragment: 'wearing a draped scarf' },
      { id: 'gloves', label: 'Gloves', fragment: 'wearing leather gloves' },
      { id: 'tattoos', label: 'Tattoos', fragment: 'with visible tattoos' },
      { id: 'piercings', label: 'Piercings', fragment: 'with facial piercings' },
      { id: 'backpack', label: 'Backpack', fragment: 'carrying a backpack' },
      { id: 'headphones', label: 'Headphones', fragment: 'wearing over-ear headphones' },
      { id: 'face-mask', label: 'Face mask', fragment: 'wearing a face mask' },
      { id: 'bandana', label: 'Bandana', fragment: 'wearing a bandana' },
      { id: 'belt', label: 'Statement belt', fragment: 'wearing a statement belt' },
      { id: 'handbag', label: 'Handbag', fragment: 'holding a designer handbag' },
    ]},
    { id: 'location', label: 'Location', options: [
      { id: 'studio', label: 'Photo studio', fragment: 'in a professional photo studio' },
      { id: 'city', label: 'City street', fragment: 'on a busy city street' },
      { id: 'forest', label: 'Forest', fragment: 'in a sunlit forest clearing' },
      { id: 'beach', label: 'Beach', fragment: 'on a sandy beach by the ocean' },
      { id: 'cafe', label: 'Cafe', fragment: 'inside a cozy cafe' },
      { id: 'rooftop', label: 'Rooftop', fragment: 'on a city rooftop overlooking skyscrapers' },
      { id: 'desert', label: 'Desert', fragment: 'in a vast desert landscape' },
      { id: 'mountains', label: 'Mountains', fragment: 'on a rugged mountain trail' },
      { id: 'library', label: 'Library', fragment: 'in an old library full of books' },
      { id: 'nightclub', label: 'Nightclub', fragment: 'in a moody neon-lit nightclub' },
      { id: 'home', label: 'Home interior', fragment: 'in a warmly lit home interior' },
      { id: 'rainy-street', label: 'Rainy street', fragment: 'on a rain-soaked street at night' },
      { id: 'snow', label: 'Snowscape', fragment: 'in a snowy winter landscape' },
      { id: 'wheat-field', label: 'Wheat field', fragment: 'in a golden wheat field' },
      { id: 'gym', label: 'Gym', fragment: 'in a modern gym' },
      { id: 'pool', label: 'Poolside', fragment: 'by a luxury poolside' },
      { id: 'office', label: 'Office', fragment: 'in a sleek corporate office' },
      { id: 'subway', label: 'Subway', fragment: 'in a subway station' },
      { id: 'garden', label: 'Garden', fragment: 'in a blooming garden' },
      { id: 'waterfall', label: 'Waterfall', fragment: 'beside a jungle waterfall' },
      { id: 'bar', label: 'Cocktail bar', fragment: 'in a dimly lit cocktail bar' },
      { id: 'alley', label: 'Graffiti alley', fragment: 'in a graffiti-covered alley' },
      { id: 'ballroom', label: 'Ballroom', fragment: 'in an opulent ballroom' },
    ]},
    { id: 'timeweather', label: 'Time & weather', options: [
      { id: 'golden-hour', label: 'Golden hour', fragment: 'during golden hour' },
      { id: 'blue-hour', label: 'Blue hour', fragment: 'during the blue hour after sunset' },
      { id: 'sunrise', label: 'Sunrise', fragment: 'at sunrise' },
      { id: 'sunset', label: 'Sunset', fragment: 'at sunset' },
      { id: 'twilight', label: 'Twilight', fragment: 'at twilight' },
      { id: 'midday', label: 'Midday sun', fragment: 'under bright midday sun' },
      { id: 'overcast', label: 'Overcast', fragment: 'under soft overcast skies' },
      { id: 'clear-sky', label: 'Clear sky', fragment: 'under a clear blue sky' },
      { id: 'cloudy', label: 'Cloudy', fragment: 'under scattered clouds' },
      { id: 'night', label: 'Night', fragment: 'at night' },
      { id: 'foggy', label: 'Foggy', fragment: 'in thick morning fog' },
      { id: 'misty', label: 'Misty', fragment: 'in soft mist' },
      { id: 'rain', label: 'Light rain', fragment: 'in light rain' },
      { id: 'drizzle', label: 'Drizzle', fragment: 'in light drizzle' },
      { id: 'storm', label: 'Stormy', fragment: 'under a dramatic stormy sky' },
      { id: 'thunderstorm', label: 'Thunderstorm', fragment: 'during a thunderstorm' },
      { id: 'snowfall', label: 'Snowfall', fragment: 'during gentle snowfall' },
      { id: 'frost', label: 'Frosty', fragment: 'on a frosty morning' },
      { id: 'windy', label: 'Windy', fragment: 'on a windy day' },
      { id: 'heatwave', label: 'Heat haze', fragment: 'in shimmering heat haze' },
      { id: 'humid', label: 'Humid', fragment: 'in humid tropical air' },
    ]},
    { id: 'pose', label: 'Pose / action', options: [
      { id: 'portrait', label: 'Facing camera', fragment: 'looking directly at the camera, relaxed expression' },
      { id: 'walking', label: 'Walking', fragment: 'walking confidently, mid-stride' },
      { id: 'sitting', label: 'Seated', fragment: 'seated, leaning slightly forward' },
      { id: 'looking-away', label: 'Looking away', fragment: 'gazing thoughtfully into the distance' },
      { id: 'over-shoulder', label: 'Over shoulder', fragment: 'glancing back over one shoulder' },
      { id: 'arms-crossed', label: 'Arms crossed', fragment: 'standing with arms crossed' },
      { id: 'candid-laugh', label: 'Candid laugh', fragment: 'caught mid-laugh, candid moment' },
      { id: 'running', label: 'Running', fragment: 'running with dynamic motion' },
      { id: 'leaning-wall', label: 'Leaning on wall', fragment: 'leaning casually against a wall' },
      { id: 'hands-pockets', label: 'Hands in pockets', fragment: 'standing relaxed with hands in pockets' },
      { id: 'jumping', label: 'Jumping', fragment: 'captured mid-jump' },
      { id: 'hands-on-hips', label: 'Hands on hips', fragment: 'standing with hands on hips' },
      { id: 'crouching', label: 'Crouching', fragment: 'crouching low' },
      { id: 'lying-down', label: 'Lying down', fragment: 'lying down relaxed' },
      { id: 'stretching', label: 'Stretching', fragment: 'stretching gracefully' },
      { id: 'dancing', label: 'Dancing', fragment: 'caught mid-dance' },
      { id: 'flexing', label: 'Flexing', fragment: 'flexing muscles confidently' },
      { id: 'reaching', label: 'Reaching', fragment: 'reaching upward' },
      { id: 'kneeling', label: 'Kneeling', fragment: 'kneeling on one knee' },
      { id: 'leaning-forward', label: 'Leaning forward', fragment: 'leaning forward toward the camera' },
      { id: 'power-pose', label: 'Power pose', fragment: 'in a confident power pose' },
    ]},
    { id: 'expression', label: 'Expression', options: [
      { id: 'smile', label: 'Warm smile', fragment: 'a warm genuine smile' },
      { id: 'serious', label: 'Serious', fragment: 'a calm serious expression' },
      { id: 'pensive', label: 'Pensive', fragment: 'a pensive, thoughtful look' },
      { id: 'joyful', label: 'Joyful', fragment: 'a joyful laughing expression' },
      { id: 'confident', label: 'Confident', fragment: 'a confident, assured gaze' },
      { id: 'melancholic', label: 'Melancholic', fragment: 'a soft melancholic expression' },
      { id: 'surprised', label: 'Surprised', fragment: 'a surprised wide-eyed look' },
      { id: 'neutral', label: 'Neutral', fragment: 'a relaxed neutral expression' },
      { id: 'smirk', label: 'Smirk', fragment: 'a playful smirk' },
      { id: 'laughing', label: 'Laughing', fragment: 'laughing heartily' },
      { id: 'angry', label: 'Angry', fragment: 'an intense angry glare' },
      { id: 'seductive', label: 'Seductive', fragment: 'a sultry seductive look' },
      { id: 'shy', label: 'Shy', fragment: 'a shy bashful expression' },
      { id: 'determined', label: 'Determined', fragment: 'a fierce determined expression' },
      { id: 'crying', label: 'Tearful', fragment: 'a tearful emotional expression' },
      { id: 'bored', label: 'Bored', fragment: 'a bored indifferent look' },
      { id: 'shocked', label: 'Shocked', fragment: 'a shocked open-mouthed look' },
      { id: 'dreamy', label: 'Dreamy', fragment: 'a soft dreamy gaze' },
      { id: 'content', label: 'Content', fragment: 'a calm content smile' },
      { id: 'winking', label: 'Winking', fragment: 'winking playfully' },
      { id: 'pouting', label: 'Pouting', fragment: 'pouting lips' },
    ]},
    { id: 'lighting', label: 'Lighting', options: [
      { id: 'softbox', label: 'Soft studio', fragment: 'soft diffused studio lighting' },
      { id: 'golden', label: 'Golden backlight', fragment: 'warm golden-hour backlight' },
      { id: 'rembrandt', label: 'Rembrandt', fragment: 'dramatic Rembrandt lighting' },
      { id: 'rim', label: 'Rim light', fragment: 'crisp rim lighting separating subject from background' },
      { id: 'neon', label: 'Neon', fragment: 'colorful neon lighting' },
      { id: 'candle', label: 'Candlelight', fragment: 'warm flickering candlelight' },
      { id: 'window', label: 'Window light', fragment: 'soft natural window light' },
      { id: 'harsh-sun', label: 'Harsh sun', fragment: 'harsh direct sunlight with strong shadows' },
      { id: 'backlit', label: 'Backlit', fragment: 'strongly backlit with lens flare' },
      { id: 'low-key', label: 'Low-key', fragment: 'moody low-key lighting' },
      { id: 'high-key', label: 'High-key', fragment: 'bright high-key lighting' },
      { id: 'split', label: 'Split light', fragment: 'dramatic split lighting' },
      { id: 'butterfly', label: 'Butterfly', fragment: 'butterfly beauty lighting' },
      { id: 'loop', label: 'Loop light', fragment: 'soft loop lighting' },
      { id: 'colored-gels', label: 'Colored gels', fragment: 'vivid colored gel lighting' },
      { id: 'firelight', label: 'Firelight', fragment: 'warm firelight glow' },
      { id: 'moonlight', label: 'Moonlight', fragment: 'cool moonlight' },
      { id: 'spotlight', label: 'Spotlight', fragment: 'a single dramatic spotlight' },
      { id: 'ambient', label: 'Ambient', fragment: 'soft ambient light' },
      { id: 'silhouette', label: 'Silhouette', fragment: 'a backlit silhouette' },
      { id: 'studio-strobe', label: 'Studio strobe', fragment: 'crisp studio strobe lighting' },
    ]},
    { id: 'camera', label: 'Camera / lens', options: [
      { id: '85mm', label: '85mm portrait', fragment: 'shot on an 85mm f/1.4 lens, shallow depth of field' },
      { id: '35mm', label: '35mm reportage', fragment: 'shot on a 35mm lens, documentary framing' },
      { id: '50mm', label: '50mm natural', fragment: 'shot on a 50mm lens, natural perspective' },
      { id: 'wide', label: 'Wide angle', fragment: 'wide-angle environmental shot' },
      { id: 'telephoto', label: 'Telephoto', fragment: 'compressed telephoto perspective' },
      { id: 'macro', label: 'Macro', fragment: 'extreme macro close-up' },
      { id: 'closeup', label: 'Close-up', fragment: 'tight close-up framing' },
      { id: 'fullbody', label: 'Full body', fragment: 'full-body composition' },
      { id: 'lowangle', label: 'Low angle', fragment: 'dramatic low-angle shot' },
      { id: 'highangle', label: 'High angle', fragment: 'high-angle overhead shot' },
      { id: 'dutch', label: 'Dutch angle', fragment: 'tilted dutch-angle framing' },
      { id: 'bokeh', label: 'Creamy bokeh', fragment: 'creamy bokeh background' },
      { id: 'portrait-crop', label: 'Portrait crop', fragment: 'tight portrait crop' },
      { id: 'cowboy-shot', label: 'Cowboy shot', fragment: 'cowboy shot from mid-thigh up' },
      { id: 'birds-eye', label: "Bird's eye", fragment: 'birds-eye overhead view' },
      { id: 'worms-eye', label: "Worm's eye", fragment: 'worms-eye low view' },
      { id: 'over-shoulder-cam', label: 'Over the shoulder', fragment: 'over-the-shoulder camera angle' },
      { id: 'fisheye', label: 'Fisheye', fragment: 'fisheye lens distortion' },
      { id: 'tilt-shift', label: 'Tilt-shift', fragment: 'tilt-shift miniature effect' },
      { id: 'drone', label: 'Drone aerial', fragment: 'aerial drone shot' },
      { id: 'first-person', label: 'First-person POV', fragment: 'first-person POV' },
    ]},
    { id: 'composition', label: 'Composition', options: [
      { id: 'rule-thirds', label: 'Rule of thirds', fragment: 'composed with the rule of thirds' },
      { id: 'centered', label: 'Centered', fragment: 'a centered symmetrical composition' },
      { id: 'symmetry', label: 'Symmetry', fragment: 'perfect symmetry' },
      { id: 'leading-lines', label: 'Leading lines', fragment: 'strong leading lines' },
      { id: 'negative-space', label: 'Negative space', fragment: 'generous negative space' },
      { id: 'frame-in-frame', label: 'Frame in frame', fragment: 'a frame-within-a-frame composition' },
      { id: 'golden-ratio', label: 'Golden ratio', fragment: 'golden-ratio composition' },
      { id: 'diagonal', label: 'Diagonal', fragment: 'dynamic diagonal composition' },
      { id: 'close-crop', label: 'Close crop', fragment: 'a tight close crop' },
      { id: 'wide-establishing', label: 'Wide establishing', fragment: 'a wide establishing composition' },
      { id: 'minimalist', label: 'Minimalist', fragment: 'a minimalist clean composition' },
      { id: 'busy-detail', label: 'Busy detail', fragment: 'a richly detailed busy composition' },
      { id: 'foreground-interest', label: 'Foreground interest', fragment: 'strong foreground interest' },
      { id: 'depth-layers', label: 'Depth layers', fragment: 'layered depth from foreground to background' },
      { id: 'reflection', label: 'Reflection', fragment: 'a reflection-based composition' },
      { id: 'silhouetted-subject', label: 'Silhouetted subject', fragment: 'subject silhouetted against the background' },
      { id: 'off-center', label: 'Off-center', fragment: 'an off-center composition' },
      { id: 'low-horizon', label: 'Low horizon', fragment: 'a low horizon line' },
      { id: 'high-horizon', label: 'High horizon', fragment: 'a high horizon line' },
      { id: 'vignette-comp', label: 'Vignette', fragment: 'a subtle vignette framing' },
      { id: 'radial', label: 'Radial', fragment: 'a radial composition' },
    ]},
    { id: 'color', label: 'Color & grade', options: [
      { id: 'warm', label: 'Warm', fragment: 'warm color grading' },
      { id: 'cool', label: 'Cool', fragment: 'cool blue color grading' },
      { id: 'teal-orange', label: 'Teal & orange', fragment: 'cinematic teal-and-orange grade' },
      { id: 'desaturated', label: 'Desaturated', fragment: 'muted desaturated palette' },
      { id: 'vibrant', label: 'Vibrant', fragment: 'vibrant saturated colors' },
      { id: 'bw', label: 'Black & white', fragment: 'black-and-white monochrome' },
      { id: 'pastel', label: 'Pastel', fragment: 'soft pastel color palette' },
      { id: 'film-stock', label: 'Film stock', fragment: 'analog film color with subtle grain' },
      { id: 'moody-dark', label: 'Moody dark', fragment: 'dark moody color grade' },
      { id: 'sepia', label: 'Sepia', fragment: 'warm sepia tones' },
      { id: 'monochrome-blue', label: 'Monochrome blue', fragment: 'monochrome blue palette' },
      { id: 'earth-tones', label: 'Earth tones', fragment: 'natural earth tones' },
      { id: 'jewel-tones', label: 'Jewel tones', fragment: 'rich jewel tones' },
      { id: 'neon-palette', label: 'Neon palette', fragment: 'vivid neon palette' },
      { id: 'muted-pastel', label: 'Muted pastel', fragment: 'muted pastel palette' },
      { id: 'high-saturation', label: 'High saturation', fragment: 'high-saturation pop colors' },
      { id: 'cinematic-grade', label: 'Cinematic grade', fragment: 'a cinematic color grade' },
      { id: 'golden-warm', label: 'Golden warm', fragment: 'golden warm tones' },
      { id: 'cold-blue', label: 'Cold blue', fragment: 'cold steely blue tones' },
      { id: 'split-tone', label: 'Split tone', fragment: 'split-toned shadows and highlights' },
      { id: 'vintage-fade', label: 'Vintage fade', fragment: 'a faded vintage color grade' },
    ]},
    { id: 'artstyle', label: 'Photo style', options: [
      { id: 'dslr', label: 'DSLR photo', fragment: 'a sharp DSLR photograph' },
      { id: 'film-35mm', label: '35mm film', fragment: 'shot on 35mm film' },
      { id: 'medium-format', label: 'Medium format', fragment: 'a medium-format film look' },
      { id: 'polaroid', label: 'Polaroid', fragment: 'a vintage Polaroid look' },
      { id: 'editorial', label: 'Editorial', fragment: 'a high-fashion editorial photo' },
      { id: 'documentary', label: 'Documentary', fragment: 'a candid documentary photo' },
      { id: 'cinematic', label: 'Cinematic still', fragment: 'a cinematic film still' },
      { id: 'fine-art', label: 'Fine art', fragment: 'a fine-art portrait' },
      { id: 'product-shot', label: 'Product shot', fragment: 'a clean product-photography style' },
      { id: 'hdr-photo', label: 'HDR', fragment: 'an HDR photograph' },
      { id: 'long-exposure', label: 'Long exposure', fragment: 'a long-exposure photograph' },
      { id: 'analog-grain', label: 'Analog grain', fragment: 'an analog photo with natural grain' },
      { id: 'bw-film', label: 'B&W film', fragment: 'classic black-and-white film' },
      { id: 'lomography', label: 'Lomography', fragment: 'a lomography look' },
      { id: 'cyberpunk-photo', label: 'Cyberpunk', fragment: 'a cyberpunk photographic style' },
      { id: 'noir', label: 'Film noir', fragment: 'a film-noir style' },
      { id: 'glamour', label: 'Glamour', fragment: 'a glamour photography style' },
      { id: 'street-photo', label: 'Street photo', fragment: 'a gritty street-photography style' },
      { id: 'studio-portrait', label: 'Studio portrait', fragment: 'a polished studio portrait' },
      { id: 'hyperreal', label: 'Hyperreal', fragment: 'a hyperrealistic render' },
      { id: 'vintage-photo', label: 'Vintage', fragment: 'a vintage photograph' },
    ]},
    { id: 'mood', label: 'Mood', options: [
      { id: 'serene', label: 'Serene', fragment: 'calm, serene atmosphere' },
      { id: 'dramatic', label: 'Dramatic', fragment: 'tense, dramatic atmosphere' },
      { id: 'joyful', label: 'Joyful', fragment: 'bright, joyful mood' },
      { id: 'mysterious', label: 'Mysterious', fragment: 'mysterious, enigmatic mood' },
      { id: 'romantic', label: 'Romantic', fragment: 'tender romantic mood' },
      { id: 'nostalgic', label: 'Nostalgic', fragment: 'warm nostalgic mood' },
      { id: 'energetic', label: 'Energetic', fragment: 'high-energy dynamic mood' },
      { id: 'somber', label: 'Somber', fragment: 'quiet somber mood' },
      { id: 'tense', label: 'Tense', fragment: 'a tense suspenseful mood' },
      { id: 'dreamy', label: 'Dreamy', fragment: 'a soft dreamy mood' },
      { id: 'ominous', label: 'Ominous', fragment: 'an ominous foreboding mood' },
      { id: 'playful', label: 'Playful', fragment: 'a lighthearted playful mood' },
      { id: 'powerful', label: 'Powerful', fragment: 'a powerful commanding mood' },
      { id: 'hopeful', label: 'Hopeful', fragment: 'a warm hopeful mood' },
      { id: 'sensual', label: 'Sensual', fragment: 'a sensual intimate mood' },
      { id: 'epic', label: 'Epic', fragment: 'an epic cinematic mood' },
      { id: 'cozy', label: 'Cozy', fragment: 'a cozy intimate mood' },
      { id: 'lonely', label: 'Lonely', fragment: 'a quiet lonely mood' },
      { id: 'triumphant', label: 'Triumphant', fragment: 'a triumphant mood' },
      { id: 'eerie', label: 'Eerie', fragment: 'an eerie unsettling mood' },
      { id: 'glamorous', label: 'Glamorous', fragment: 'a glamorous luxurious mood' },
    ]},
    { id: 'quality', label: 'Quality boosters', options: [
      { id: 'skin', label: 'Skin detail', fragment: 'hyper-detailed skin texture with visible pores, realistic subsurface scattering' },
      { id: 'sharp', label: 'Sharp focus', fragment: 'tack-sharp focus, fine detail' },
      { id: 'photoreal', label: 'Photorealism', fragment: 'photorealistic, natural color grading, 8k' },
      { id: 'hdr', label: 'HDR', fragment: 'high dynamic range, balanced highlights and shadows' },
      { id: 'studio-quality', label: 'Studio quality', fragment: 'professional studio photography quality' },
      { id: 'detailed-eyes', label: 'Detailed eyes', fragment: 'highly detailed realistic eyes with catchlights' },
      { id: 'raw-photo', label: 'Raw photo', fragment: 'raw photo, ultra-realistic, lifelike' },
      { id: 'award', label: 'Award-winning', fragment: 'award-winning photography, masterful composition' },
      { id: '8k', label: '8K detail', fragment: 'ultra-detailed 8k resolution' },
      { id: 'dof', label: 'Depth of field', fragment: 'beautiful natural depth of field' },
      { id: 'film-grain-q', label: 'Film grain', fragment: 'subtle cinematic film grain' },
      { id: 'ultra-detail', label: 'Ultra detail', fragment: 'ultra-detailed textures' },
      { id: 'realistic-lighting', label: 'Realistic lighting', fragment: 'physically accurate realistic lighting' },
      { id: 'pro-photo', label: 'Pro photography', fragment: 'professional photography, masterful' },
      { id: 'natural-skin', label: 'Natural skin', fragment: 'natural realistic skin tones' },
      { id: 'crisp', label: 'Crisp detail', fragment: 'crisp clean details' },
      { id: 'lifelike', label: 'Lifelike', fragment: 'lifelike and believable' },
      { id: 'high-fidelity', label: 'High fidelity', fragment: 'high-fidelity rendering' },
      { id: 'cinematic-q', label: 'Cinematic', fragment: 'cinematic quality' },
      { id: 'magazine', label: 'Magazine cover', fragment: 'magazine-cover quality' },
      { id: 'dramatic-contrast', label: 'Dramatic contrast', fragment: 'rich dramatic contrast' },
    ]},
  ],
  anime: [
    { id: 'subject', label: 'Subject / character', options: [
      { id: 'heroine', label: 'Heroine', fragment: '1girl, solo' },
      { id: 'hero', label: 'Hero', fragment: '1boy, solo' },
      { id: 'mage', label: 'Mage', fragment: '1girl, solo, witch_hat, robe' },
      { id: 'knight', label: 'Knight', fragment: '1girl, solo, armor' },
      { id: 'schoolgirl', label: 'Schoolgirl', fragment: '1girl, solo, school_uniform' },
      { id: 'schoolboy', label: 'Schoolboy', fragment: '1boy, solo, school_uniform' },
      { id: 'catgirl', label: 'Catgirl', fragment: '1girl, solo, cat_ears, cat_tail' },
      { id: 'samurai', label: 'Samurai', fragment: '1girl, solo, samurai, katana' },
      { id: 'idol', label: 'Idol', fragment: '1girl, solo, idol' },
      { id: 'witch', label: 'Witch', fragment: '1girl, solo, witch, witch_hat' },
      { id: 'ninja', label: 'Ninja', fragment: '1girl, solo, ninja' },
      { id: 'demon-lord', label: 'Demon lord', fragment: '1boy, solo, demon, horns' },
      { id: 'chibi', label: 'Chibi', fragment: 'chibi, 1girl, solo' },
      { id: 'angel', label: 'Angel', fragment: '1girl, solo, angel_wings, halo' },
      { id: 'demon-girl', label: 'Demon girl', fragment: '1girl, solo, horns, demon_girl' },
      { id: 'elf', label: 'Elf', fragment: '1girl, solo, elf, pointy_ears' },
      { id: 'robot-girl', label: 'Android girl', fragment: '1girl, solo, robot_girl, mechanical_parts' },
      { id: 'princess', label: 'Princess', fragment: '1girl, solo, princess, tiara' },
      { id: 'vampire', label: 'Vampire', fragment: '1girl, solo, vampire, fangs' },
      { id: 'shrine-maiden', label: 'Shrine maiden', fragment: '1girl, solo, miko' },
      { id: 'mecha-pilot', label: 'Mecha pilot', fragment: '1girl, solo, pilot_suit' },
    ]},
    { id: 'bodytype', label: 'Body type', options: [
      { id: 'slim', label: 'Slim', fragment: 'slim' },
      { id: 'petite', label: 'Petite', fragment: 'petite' },
      { id: 'athletic', label: 'Athletic', fragment: 'toned' },
      { id: 'curvy', label: 'Curvy', fragment: 'curvy, wide_hips' },
      { id: 'tall', label: 'Tall', fragment: 'tall' },
      { id: 'muscular', label: 'Muscular', fragment: 'muscular' },
      { id: 'chibi-proportions', label: 'Chibi proportions', fragment: 'chibi' },
      { id: 'lithe', label: 'Lithe', fragment: 'slender' },
      { id: 'muscle-girl', label: 'Muscle girl', fragment: 'muscular_female, abs' },
      { id: 'female-bodybuilder', label: 'Bodybuilder (f)', fragment: 'muscular_female, bodybuilder' },
      { id: 'shredded-f', label: 'Shredded (f)', fragment: 'muscular_female, six_pack' },
      { id: 'amazon-f', label: 'Amazonian (f)', fragment: 'amazonian, muscular_female' },
      { id: 'average', label: 'Average', fragment: 'average_build' },
      { id: 'voluptuous', label: 'Voluptuous', fragment: 'curvy, large_breasts' },
      { id: 'toned', label: 'Toned', fragment: 'toned, abs' },
      { id: 'broad-hero', label: 'Broad heroic', fragment: 'muscular_male, broad_shoulders' },
      { id: 'lanky', label: 'Lanky', fragment: 'tall, slender' },
      { id: 'small-chibi', label: 'Tiny chibi', fragment: 'mini_girl, chibi' },
      { id: 'elegant-slender', label: 'Elegant slender', fragment: 'slender, tall' },
      { id: 'statuesque-amazon', label: 'Statuesque', fragment: 'amazonian, tall' },
      { id: 'stocky-brawler', label: 'Stocky brawler', fragment: 'muscular, stocky' },
    ]},
    { id: 'complexion', label: 'Skin tone', options: [
      { id: 'fair', label: 'Fair', fragment: 'pale_skin' },
      { id: 'light', label: 'Light', fragment: 'fair_skin' },
      { id: 'rosy', label: 'Rosy', fragment: 'fair_skin, blush' },
      { id: 'pale', label: 'Porcelain', fragment: 'very_pale_skin' },
      { id: 'peach', label: 'Peach', fragment: 'white_skin' },
      { id: 'warm-beige', label: 'Warm beige', fragment: 'light_brown_skin' },
      { id: 'olive', label: 'Olive', fragment: 'olive_skin' },
      { id: 'tan', label: 'Tan (gyaru)', fragment: 'tan' },
      { id: 'sun-kissed', label: 'Sun-kissed', fragment: 'tan, tanlines' },
      { id: 'golden', label: 'Golden', fragment: 'tan, shiny_skin' },
      { id: 'bronze', label: 'Bronze', fragment: 'dark_skin' },
      { id: 'caramel', label: 'Caramel', fragment: 'dark_skin, dark-skinned_female' },
      { id: 'dark', label: 'Dark', fragment: 'very_dark_skin' },
      { id: 'deep-brown', label: 'Deep brown', fragment: 'dark-skinned_female' },
      { id: 'ghostly', label: 'Ghostly pale', fragment: 'pale_skin, ghost' },
      { id: 'blue-skin', label: 'Blue', fragment: 'blue_skin, colored_skin' },
      { id: 'green-skin', label: 'Green', fragment: 'green_skin, colored_skin' },
      { id: 'grey-skin', label: 'Ashen grey', fragment: 'grey_skin, colored_skin' },
      { id: 'freckled', label: 'Freckled', fragment: 'freckles' },
      { id: 'glowing', label: 'Glowing', fragment: 'shiny_skin, glowing' },
      { id: 'flawless', label: 'Flawless', fragment: 'smooth_skin' },
    ]},
    { id: 'hair', label: 'Hair', options: [
      { id: 'long-twin', label: 'Twin-tails', fragment: 'twintails, long_hair' },
      { id: 'short-spiky', label: 'Short spiky', fragment: 'spiky_hair, short_hair' },
      { id: 'silver-long', label: 'Long silver', fragment: 'silver_hair, long_hair' },
      { id: 'pink-bob', label: 'Pink bob', fragment: 'pink_hair, bob_cut' },
      { id: 'blue-ponytail', label: 'Blue ponytail', fragment: 'blue_hair, ponytail' },
      { id: 'ahoge', label: 'Ahoge', fragment: 'ahoge' },
      { id: 'gradient', label: 'Gradient', fragment: 'gradient_hair, multicolored_hair' },
      { id: 'braided-crown', label: 'Braided crown', fragment: 'crown_braid, braid' },
      { id: 'messy-shoulder', label: 'Messy shoulder', fragment: 'messy_hair, medium_hair' },
      { id: 'hime', label: 'Hime cut', fragment: 'hime_cut' },
      { id: 'drill-curls', label: 'Drill curls', fragment: 'drill_hair' },
      { id: 'long-straight-black', label: 'Long black', fragment: 'black_hair, long_hair, straight_hair' },
      { id: 'short-bob', label: 'Short bob', fragment: 'bob_cut, short_hair' },
      { id: 'side-ponytail', label: 'Side ponytail', fragment: 'side_ponytail' },
      { id: 'long-wavy', label: 'Long wavy', fragment: 'wavy_hair, long_hair' },
      { id: 'rainbow', label: 'Rainbow', fragment: 'rainbow_hair, multicolored_hair' },
      { id: 'white-long', label: 'Long white', fragment: 'white_hair, long_hair' },
      { id: 'red-spiky', label: 'Red spiky', fragment: 'red_hair, spiky_hair' },
      { id: 'green-twin', label: 'Green twin-tails', fragment: 'green_hair, twintails' },
      { id: 'purple-long', label: 'Long purple', fragment: 'purple_hair, long_hair' },
      { id: 'odango', label: 'Odango buns', fragment: 'double_bun, hair_bun' },
    ]},
    { id: 'clothing', label: 'Outfit', options: [
      { id: 'uniform', label: 'School uniform', fragment: 'school_uniform' },
      { id: 'sailor-uniform', label: 'Sailor uniform', fragment: 'serafuku, sailor_collar' },
      { id: 'armor', label: 'Fantasy armor', fragment: 'armor, fantasy' },
      { id: 'kimono', label: 'Kimono', fragment: 'kimono, japanese_clothes' },
      { id: 'yukata', label: 'Yukata', fragment: 'yukata' },
      { id: 'magical-girl', label: 'Magical girl', fragment: 'magical_girl, frills' },
      { id: 'battle-suit', label: 'Battle suit', fragment: 'bodysuit, skin_tight' },
      { id: 'gothic-lolita', label: 'Gothic lolita', fragment: 'gothic_lolita, lolita_fashion' },
      { id: 'hoodie', label: 'Casual hoodie', fragment: 'hoodie, casual' },
      { id: 'maid', label: 'Maid outfit', fragment: 'maid, maid_headdress, apron' },
      { id: 'miko-outfit', label: 'Miko outfit', fragment: 'miko, hakama' },
      { id: 'cloak', label: 'Traveler cloak', fragment: 'cloak, hood' },
      { id: 'racing-suit', label: 'Racing suit', fragment: 'racing_suit, gloves' },
      { id: 'track-suit', label: 'Track suit', fragment: 'track_jacket, tracksuit' },
      { id: 'gym-uniform', label: 'Gym uniform', fragment: 'gym_uniform, buruma' },
      { id: 'haori', label: 'Haori & hakama', fragment: 'haori, hakama' },
      { id: 'ninja-outfit', label: 'Ninja outfit', fragment: 'ninja, ninja_mask' },
      { id: 'idol-costume', label: 'Idol costume', fragment: 'idol, stage_costume' },
      { id: 'winter-coat', label: 'Winter coat', fragment: 'winter_clothes, coat' },
      { id: 'nun-habit', label: 'Nun habit', fragment: 'nun, habit' },
      { id: 'china-dress', label: 'China dress', fragment: 'china_dress, pelvic_curtain' },
    ]},
    { id: 'womensclothing', label: "Women's clothing", options: [
      { id: 'evening-gown', label: 'Evening gown', fragment: 'evening_gown, dress' },
      { id: 'cocktail-dress', label: 'Cocktail dress', fragment: 'cocktail_dress' },
      { id: 'sundress', label: 'Sundress', fragment: 'sundress' },
      { id: 'mini-skirt', label: 'Mini skirt', fragment: 'miniskirt' },
      { id: 'pleated-skirt', label: 'Pleated skirt', fragment: 'pleated_skirt' },
      { id: 'pencil-skirt', label: 'Pencil skirt', fragment: 'pencil_skirt' },
      { id: 'blouse-skirt', label: 'Blouse & skirt', fragment: 'blouse, skirt' },
      { id: 'crop-top', label: 'Crop top', fragment: 'crop_top, midriff' },
      { id: 'off-shoulder', label: 'Off-shoulder', fragment: 'off-shoulder, dress' },
      { id: 'bodycon', label: 'Bodycon dress', fragment: 'form-fitting_dress' },
      { id: 'maxi-dress', label: 'Maxi dress', fragment: 'long_dress' },
      { id: 'wrap-dress', label: 'Wrap dress', fragment: 'wrap_dress' },
      { id: 'halter-dress', label: 'Halter dress', fragment: 'halterneck, dress' },
      { id: 'jumpsuit', label: 'Jumpsuit', fragment: 'jumpsuit' },
      { id: 'overall-skirt', label: 'Overall skirt', fragment: 'overall_skirt, suspenders' },
      { id: 'sweater-dress', label: 'Sweater dress', fragment: 'sweater_dress' },
      { id: 'ballgown', label: 'Ballgown', fragment: 'ballgown, dress' },
      { id: 'sailor-dress', label: 'Sailor dress', fragment: 'sailor_dress' },
      { id: 'frilly-dress', label: 'Frilly dress', fragment: 'frilled_dress, frills' },
      { id: 'leather-skirt', label: 'Leather skirt', fragment: 'leather_skirt' },
      { id: 'turtleneck-dress', label: 'Turtleneck dress', fragment: 'sweater_dress, turtleneck' },
    ]},
    { id: 'underwear', label: 'Underwear', options: [
      { id: 'lingerie', label: 'Lace lingerie', fragment: 'lingerie, lace' },
      { id: 'bra-panties', label: 'Bra & panties', fragment: 'bra, panties' },
      { id: 'thong', label: 'Thong', fragment: 'thong' },
      { id: 'boyshorts', label: 'Boyshorts', fragment: 'boyshorts, panties' },
      { id: 'babydoll', label: 'Babydoll', fragment: 'babydoll' },
      { id: 'teddy', label: 'Teddy', fragment: 'teddy' },
      { id: 'corset', label: 'Corset', fragment: 'corset' },
      { id: 'bustier', label: 'Bustier', fragment: 'bustier' },
      { id: 'garter', label: 'Garter & stockings', fragment: 'garter_belt, thighhighs' },
      { id: 'chemise', label: 'Chemise', fragment: 'chemise' },
      { id: 'lace-leotard', label: 'Lace bodysuit', fragment: 'leotard, lace' },
      { id: 'sports-bra', label: 'Sports bra', fragment: 'sports_bra, shorts' },
      { id: 'boxers', label: 'Boxers', fragment: 'boxers' },
      { id: 'briefs', label: 'Briefs', fragment: 'briefs' },
      { id: 'camisole', label: 'Camisole', fragment: 'camisole' },
      { id: 'slip', label: 'Slip', fragment: 'slip' },
      { id: 'lace-set', label: 'Lace set', fragment: 'lace_panties, lace_bra' },
      { id: 'strappy', label: 'Strappy lingerie', fragment: 'strap_gap, lingerie' },
      { id: 'see-through', label: 'See-through', fragment: 'see-through, underwear' },
      { id: 'ribbon-lingerie', label: 'Ribbon lingerie', fragment: 'ribbon, lingerie' },
      { id: 'pasties', label: 'Pasties', fragment: 'pasties' },
    ]},
    { id: 'bikinis', label: 'Bikinis / swimwear', options: [
      { id: 'string-bikini', label: 'String bikini', fragment: 'string_bikini' },
      { id: 'side-tie-bikini', label: 'Side-tie bikini', fragment: 'bikini, side-tie_bikini' },
      { id: 'bandeau-bikini', label: 'Bandeau bikini', fragment: 'strapless_bikini' },
      { id: 'halter-bikini', label: 'Halter bikini', fragment: 'halterneck, bikini' },
      { id: 'sporty-bikini', label: 'Sporty bikini', fragment: 'sports_bikini' },
      { id: 'micro-bikini', label: 'Micro bikini', fragment: 'micro_bikini' },
      { id: 'school-swimsuit', label: 'School swimsuit', fragment: 'school_swimsuit' },
      { id: 'one-piece', label: 'One-piece', fragment: 'one-piece_swimsuit' },
      { id: 'thong-bikini', label: 'Thong bikini', fragment: 'thong, bikini' },
      { id: 'frilled-bikini', label: 'Frilled bikini', fragment: 'frilled_bikini' },
      { id: 'highleg', label: 'High-leg swimsuit', fragment: 'highleg_swimsuit' },
      { id: 'competition-swimsuit', label: 'Competition swimsuit', fragment: 'competition_swimsuit' },
      { id: 'tankini', label: 'Tankini', fragment: 'tankini' },
      { id: 'o-ring-bikini', label: 'O-ring bikini', fragment: 'o-ring_bikini' },
      { id: 'front-tie-bikini', label: 'Front-tie bikini', fragment: 'front-tie_bikini' },
      { id: 'crochet-bikini', label: 'Crochet bikini', fragment: 'crocheted, bikini' },
      { id: 'lace-bikini', label: 'Lace bikini', fragment: 'bikini, lace' },
      { id: 'polka-bikini', label: 'Polka-dot bikini', fragment: 'polka_dot_bikini' },
      { id: 'striped-bikini', label: 'Striped bikini', fragment: 'striped_bikini' },
      { id: 'slingshot', label: 'Slingshot swimsuit', fragment: 'slingshot_swimsuit' },
      { id: 'floral-bikini', label: 'Floral bikini', fragment: 'floral_print, bikini' },
    ]},
    { id: 'accessories', label: 'Accessories', options: [
      { id: 'none', label: 'None', fragment: '' },
      { id: 'glasses', label: 'Glasses', fragment: 'glasses' },
      { id: 'cat-ears', label: 'Cat ears', fragment: 'cat_ears, animal_ears' },
      { id: 'ribbon', label: 'Hair ribbon', fragment: 'hair_ribbon, ribbon' },
      { id: 'hairclip', label: 'Hair clip', fragment: 'hair_ornament, hairclip' },
      { id: 'choker', label: 'Choker', fragment: 'choker' },
      { id: 'earrings', label: 'Earrings', fragment: 'earrings' },
      { id: 'necklace', label: 'Necklace', fragment: 'necklace, jewelry' },
      { id: 'headband', label: 'Headband', fragment: 'headband' },
      { id: 'witch-hat', label: 'Witch hat', fragment: 'witch_hat, hat' },
      { id: 'crown', label: 'Crown', fragment: 'crown' },
      { id: 'halo', label: 'Halo', fragment: 'halo' },
      { id: 'horns', label: 'Horns', fragment: 'horns' },
      { id: 'wings', label: 'Wings', fragment: 'wings, feathered_wings' },
      { id: 'tail', label: 'Tail', fragment: 'tail, animal_tail' },
      { id: 'gauntlets', label: 'Gauntlets', fragment: 'gauntlets, armor' },
      { id: 'thigh-highs', label: 'Thigh-highs', fragment: 'thighhighs' },
      { id: 'scarf', label: 'Scarf', fragment: 'scarf' },
      { id: 'backpack', label: 'Backpack', fragment: 'backpack, bag' },
      { id: 'eyepatch', label: 'Eyepatch', fragment: 'eyepatch' },
      { id: 'face-mask', label: 'Ninja mask', fragment: 'mask, covered_mouth' },
    ]},
    { id: 'location', label: 'Environment', options: [
      { id: 'rooftop', label: 'School rooftop', fragment: 'rooftop, sky' },
      { id: 'city-night', label: 'Neon city', fragment: 'cityscape, night, neon_lights, cyberpunk' },
      { id: 'sakura', label: 'Cherry blossoms', fragment: 'cherry_blossoms, petals' },
      { id: 'classroom', label: 'Classroom', fragment: 'classroom, indoors' },
      { id: 'fantasy-forest', label: 'Enchanted forest', fragment: 'forest, fantasy, glowing' },
      { id: 'floating-islands', label: 'Sky islands', fragment: 'floating_island, sky' },
      { id: 'shrine', label: 'Shrine', fragment: 'shrine, torii' },
      { id: 'battlefield', label: 'Battlefield', fragment: 'battlefield, war' },
      { id: 'seaside', label: 'Seaside town', fragment: 'ocean, beach, town' },
      { id: 'magic-library', label: 'Magic library', fragment: 'library, books, magic' },
      { id: 'festival', label: 'Summer festival', fragment: 'festival, lantern' },
      { id: 'ruined-castle', label: 'Ruined castle', fragment: 'ruins, castle' },
      { id: 'starry-sky', label: 'Starry sky', fragment: 'starry_sky, night_sky, star_(sky)' },
      { id: 'cafe', label: 'Anime cafe', fragment: 'cafe, indoors' },
      { id: 'dojo', label: 'Dojo', fragment: 'dojo, tatami' },
      { id: 'onsen', label: 'Hot spring', fragment: 'onsen, steam' },
      { id: 'space-station', label: 'Space station', fragment: 'space, science_fiction, spacecraft_interior' },
      { id: 'mecha-hangar', label: 'Mecha hangar', fragment: 'hangar, mecha, science_fiction' },
      { id: 'flower-field', label: 'Flower field', fragment: 'flower_field, flowers' },
      { id: 'train', label: 'Train', fragment: 'train_interior, train' },
      { id: 'castle-town', label: 'Castle town', fragment: 'town, castle, fantasy' },
    ]},
    { id: 'timeweather', label: 'Time & weather', options: [
      { id: 'sunset', label: 'Sunset', fragment: 'sunset, orange_sky' },
      { id: 'night-stars', label: 'Starry night', fragment: 'night, starry_sky' },
      { id: 'dawn', label: 'Dawn', fragment: 'sunrise, morning' },
      { id: 'midday', label: 'Midday', fragment: 'day, sunlight' },
      { id: 'golden-hour', label: 'Golden hour', fragment: 'golden_hour, backlighting' },
      { id: 'twilight', label: 'Twilight', fragment: 'twilight, gradient_sky' },
      { id: 'rain', label: 'Gentle rain', fragment: 'rain' },
      { id: 'snow', label: 'Snowfall', fragment: 'snow, snowing' },
      { id: 'cherry-petals', label: 'Cherry petals', fragment: 'falling_petals, cherry_blossoms' },
      { id: 'storm', label: 'Lightning storm', fragment: 'lightning, storm' },
      { id: 'aurora', label: 'Aurora', fragment: 'aurora' },
      { id: 'fog', label: 'Foggy', fragment: 'fog' },
      { id: 'clear-sky', label: 'Clear sky', fragment: 'blue_sky, clouds' },
      { id: 'cloudy', label: 'Cloudy', fragment: 'cloudy_sky' },
      { id: 'rainbow', label: 'Rainbow', fragment: 'rainbow' },
      { id: 'falling-leaves', label: 'Autumn leaves', fragment: 'autumn_leaves, falling_leaves' },
      { id: 'fireflies', label: 'Fireflies', fragment: 'firefly' },
      { id: 'meteor-shower', label: 'Meteor shower', fragment: 'shooting_star' },
      { id: 'windy', label: 'Windy', fragment: 'wind, floating_hair' },
      { id: 'heat-haze', label: 'Summer heat', fragment: 'summer, heat_haze' },
      { id: 'moonlit', label: 'Moonlit', fragment: 'moonlight, full_moon' },
    ]},
    { id: 'pose', label: 'Pose / action', options: [
      { id: 'dynamic', label: 'Dynamic action', fragment: 'dynamic_pose, action, motion_lines' },
      { id: 'standing', label: 'Standing portrait', fragment: 'standing, looking_at_viewer' },
      { id: 'casting', label: 'Casting a spell', fragment: 'magic, casting_spell' },
      { id: 'sword-draw', label: 'Drawing a sword', fragment: 'holding_sword, unsheathing' },
      { id: 'running', label: 'Running', fragment: 'running' },
      { id: 'jumping', label: 'Leaping', fragment: 'jumping' },
      { id: 'sitting-grass', label: 'Sitting on grass', fragment: 'sitting, on_grass' },
      { id: 'peace-sign', label: 'Peace sign', fragment: 'peace_sign, v' },
      { id: 'floating', label: 'Floating', fragment: 'floating' },
      { id: 'back-to-back', label: 'Back-to-back', fragment: 'back-to-back' },
      { id: 'fighting-stance', label: 'Fighting stance', fragment: 'fighting_stance, martial_arts' },
      { id: 'transformation', label: 'Transformation', fragment: 'magical_girl, transformation' },
      { id: 'waving', label: 'Waving', fragment: 'waving, arm_up' },
      { id: 'hands-on-hips', label: 'Hands on hips', fragment: 'hands_on_hips' },
      { id: 'lying-down', label: 'Lying down', fragment: 'lying, on_back' },
      { id: 'crouching', label: 'Crouching', fragment: 'squatting' },
      { id: 'flying', label: 'Flying', fragment: 'flying' },
      { id: 'bowing', label: 'Bowing', fragment: 'bowing' },
      { id: 'chibi-pose', label: 'Chibi pose', fragment: 'chibi, :3' },
      { id: 'wind-blown', label: 'Wind-blown', fragment: 'wind, floating_hair, clothes_lift' },
      { id: 'dramatic-point', label: 'Dramatic point', fragment: 'pointing, pointing_at_viewer' },
    ]},
    { id: 'expression', label: 'Expression', options: [
      { id: 'determined', label: 'Determined', fragment: 'serious, clenched_teeth' },
      { id: 'smiling', label: 'Cheerful smile', fragment: 'smile, open_mouth' },
      { id: 'blushing', label: 'Blushing', fragment: 'blush, embarrassed' },
      { id: 'crying', label: 'Teary', fragment: 'tears, crying' },
      { id: 'smug', label: 'Smug grin', fragment: 'smug, smirk' },
      { id: 'shocked', label: 'Shocked', fragment: 'surprised, shaded_face' },
      { id: 'serene', label: 'Serene', fragment: 'closed_eyes, smile' },
      { id: 'angry', label: 'Angry', fragment: 'angry, anger_vein' },
      { id: 'tsundere', label: 'Tsundere pout', fragment: 'tsundere, pout' },
      { id: 'yandere', label: 'Yandere smile', fragment: 'yandere, empty_eyes' },
      { id: 'wink', label: 'Wink', fragment: 'wink, one_eye_closed' },
      { id: 'surprised', label: 'Surprised', fragment: 'surprised, parted_lips' },
      { id: 'sleepy', label: 'Sleepy', fragment: 'sleepy, half-closed_eyes' },
      { id: 'laughing', label: 'Laughing', fragment: 'laughing, open_mouth' },
      { id: 'cool', label: 'Cool', fragment: 'expressionless' },
      { id: 'teary-smile', label: 'Teary smile', fragment: 'tears, smile' },
      { id: 'mischievous', label: 'Mischievous', fragment: 'evil_grin' },
      { id: 'embarrassed', label: 'Embarrassed', fragment: 'embarrassed, nervous_sweat' },
      { id: 'fierce', label: 'Fierce', fragment: 'angry, fang' },
      { id: 'dreamy', label: 'Dreamy', fragment: 'heart-shaped_eyes' },
      { id: 'deadpan', label: 'Deadpan', fragment: 'expressionless, half-closed_eyes' },
    ]},
    { id: 'lighting', label: 'Lighting', options: [
      { id: 'rim', label: 'Rim light', fragment: 'rim_lighting' },
      { id: 'sunset', label: 'Sunset glow', fragment: 'sunset, orange_glow' },
      { id: 'neon', label: 'Neon glow', fragment: 'neon_lights' },
      { id: 'magical-glow', label: 'Magical glow', fragment: 'glowing, magic' },
      { id: 'god-rays', label: 'God rays', fragment: 'light_rays, sunbeam' },
      { id: 'moonlight', label: 'Moonlight', fragment: 'moonlight' },
      { id: 'sparkle', label: 'Sparkle bokeh', fragment: 'sparkle, bokeh' },
      { id: 'spotlight', label: 'Spotlight', fragment: 'spotlight' },
      { id: 'backlit', label: 'Backlit halo', fragment: 'backlighting, silhouette' },
      { id: 'soft-ambient', label: 'Soft ambient', fragment: 'soft_lighting' },
      { id: 'dramatic-shadow', label: 'Dramatic shadow', fragment: 'dramatic_shadows, high_contrast' },
      { id: 'lens-flare', label: 'Lens flare', fragment: 'lens_flare' },
      { id: 'golden-hour-l', label: 'Golden hour', fragment: 'sunlight, golden' },
      { id: 'colored-rim', label: 'Colored rim', fragment: 'rim_lighting, colorful' },
      { id: 'glowing-aura', label: 'Glowing aura', fragment: 'aura, glowing' },
      { id: 'candlelight', label: 'Candlelight', fragment: 'candlelight' },
      { id: 'firelight', label: 'Firelight', fragment: 'firelight, fire' },
      { id: 'cool-blue', label: 'Cool blue', fragment: 'blue_theme, cold_lighting' },
      { id: 'stage-lights', label: 'Stage lights', fragment: 'stage_lights' },
      { id: 'dappled', label: 'Dappled sun', fragment: 'dappled_sunlight' },
      { id: 'starlight', label: 'Starlight', fragment: 'faint_starlight' },
    ]},
    { id: 'camera', label: 'Framing', options: [
      { id: 'closeup', label: 'Close-up', fragment: 'close-up' },
      { id: 'fullbody', label: 'Full body', fragment: 'full_body' },
      { id: 'lowangle', label: 'Low angle', fragment: 'from_below' },
      { id: 'highangle', label: 'High angle', fragment: 'from_above' },
      { id: 'dutch', label: 'Dutch angle', fragment: 'dutch_angle' },
      { id: 'wide-scenery', label: 'Wide scenery', fragment: 'scenery, wide_shot' },
      { id: 'portrait', label: 'Portrait', fragment: 'portrait' },
      { id: 'action-cam', label: 'Action cam', fragment: 'dynamic_angle' },
      { id: 'profile', label: 'Side profile', fragment: 'profile, from_side' },
      { id: 'birds-eye', label: "Bird's eye", fragment: "from_above, bird's-eye_view" },
      { id: 'worms-eye', label: "Worm's eye", fragment: "from_below, worm's-eye_view" },
      { id: 'cowboy-shot', label: 'Cowboy shot', fragment: 'cowboy_shot' },
      { id: 'extreme-closeup', label: 'Eye close-up', fragment: 'close-up, eye_focus' },
      { id: 'over-shoulder', label: 'Over shoulder', fragment: 'from_behind' },
      { id: 'dynamic-perspective', label: 'Dynamic perspective', fragment: 'foreshortening' },
      { id: 'fisheye', label: 'Fisheye', fragment: 'fisheye' },
      { id: 'pov', label: 'First-person POV', fragment: 'pov' },
      { id: 'wide-action', label: 'Wide action', fragment: 'wide_shot, action' },
      { id: 'dramatic-zoom', label: 'Dramatic zoom', fragment: 'emphasis_lines' },
      { id: 'split-panel', label: 'Manga panel', fragment: 'multiple_views' },
      { id: 'upshot', label: 'Up-shot', fragment: 'from_below, looking_at_viewer' },
    ]},
    { id: 'composition', label: 'Composition', options: [
      { id: 'rule-thirds', label: 'Rule of thirds', fragment: 'rule_of_thirds' },
      { id: 'centered', label: 'Centered', fragment: 'centered, symmetry' },
      { id: 'symmetry', label: 'Symmetry', fragment: 'symmetry' },
      { id: 'dynamic-diagonal', label: 'Diagonal', fragment: 'dutch_angle, dynamic' },
      { id: 'speed-lines', label: 'Speed lines', fragment: 'speed_lines, emphasis_lines' },
      { id: 'negative-space', label: 'Negative space', fragment: 'simple_background, negative_space' },
      { id: 'close-crop', label: 'Close crop', fragment: 'close-up, cropped' },
      { id: 'wide-establishing', label: 'Wide establishing', fragment: 'scenery, establishing_shot' },
      { id: 'depth-layers', label: 'Depth layers', fragment: 'depth_of_field, blurry_foreground' },
      { id: 'foreground-frame', label: 'Foreground frame', fragment: 'framed, foreground' },
      { id: 'radial', label: 'Radial burst', fragment: 'radial, emphasis_lines' },
      { id: 'minimalist', label: 'Minimalist', fragment: 'minimalism, simple_background' },
      { id: 'detailed-busy', label: 'Detailed busy', fragment: 'detailed, intricate' },
      { id: 'silhouette-comp', label: 'Silhouette', fragment: 'silhouette' },
      { id: 'low-angle-hero', label: 'Hero low-angle', fragment: 'from_below, heroic' },
      { id: 'spiral', label: 'Spiral', fragment: 'spiral, swirl' },
      { id: 'off-center', label: 'Off-center', fragment: 'off-center' },
      { id: 'panoramic', label: 'Panoramic', fragment: 'panorama, wide_shot' },
      { id: 'vignette-comp', label: 'Vignette', fragment: 'vignetting' },
      { id: 'motion-blur', label: 'Motion blur', fragment: 'motion_blur' },
      { id: 'frame-in-frame', label: 'Frame in frame', fragment: 'framed, window' },
    ]},
    { id: 'color', label: 'Color palette', options: [
      { id: 'vivid', label: 'Vivid', fragment: 'vibrant, colorful' },
      { id: 'pastel', label: 'Pastel', fragment: 'pastel_colors' },
      { id: 'vibrant-neon', label: 'Neon', fragment: 'neon_palette, colorful' },
      { id: 'warm-sunset', label: 'Warm sunset', fragment: 'orange_theme, warm_colors' },
      { id: 'cool-night', label: 'Cool night', fragment: 'blue_theme, dark' },
      { id: 'mono-accent', label: 'Mono accent', fragment: 'monochrome, spot_color' },
      { id: 'dreamy', label: 'Dreamy', fragment: 'pastel_colors, soft_focus' },
      { id: 'high-contrast', label: 'High contrast', fragment: 'high_contrast' },
      { id: 'sepia', label: 'Sepia', fragment: 'sepia' },
      { id: 'earth-tones', label: 'Earth tones', fragment: 'muted_color, brown_theme' },
      { id: 'jewel-tones', label: 'Jewel tones', fragment: 'jewel_tones, saturated' },
      { id: 'candy', label: 'Candy colors', fragment: 'colorful, bright' },
      { id: 'muted', label: 'Muted', fragment: 'muted_color' },
      { id: 'sunset-gradient', label: 'Sunset gradient', fragment: 'gradient, orange_theme' },
      { id: 'cyberpunk-palette', label: 'Cyberpunk', fragment: 'neon_palette, purple_theme' },
      { id: 'monochrome', label: 'Monochrome', fragment: 'monochrome, greyscale' },
      { id: 'watercolor-hue', label: 'Watercolor', fragment: 'watercolor_(medium), soft_colors' },
      { id: 'high-key-color', label: 'High-key', fragment: 'bright, high_key' },
      { id: 'dark-moody', label: 'Dark moody', fragment: 'dark, muted_color' },
      { id: 'rainbow-pop', label: 'Rainbow pop', fragment: 'rainbow, colorful' },
      { id: 'duotone', label: 'Duotone', fragment: 'two-tone, duotone' },
    ]},
    { id: 'artstyle', label: 'Art style', options: [
      { id: 'modern-anime', label: 'Modern anime', fragment: 'anime_screencap, anime_coloring' },
      { id: '90s-anime', label: '90s anime', fragment: 'retro_artstyle, 1990s_(style)' },
      { id: 'shoujo', label: 'Shoujo', fragment: 'shoujo_(style), sparkle' },
      { id: 'shounen', label: 'Shounen', fragment: 'shounen_(style), action' },
      { id: 'chibi-style', label: 'Chibi', fragment: 'chibi' },
      { id: 'watercolor', label: 'Watercolor', fragment: 'watercolor_(medium), traditional_media' },
      { id: 'cel-shaded', label: 'Cel-shaded', fragment: 'cel_shading, flat_color' },
      { id: 'painterly', label: 'Painterly', fragment: 'painterly, impasto' },
      { id: 'manga-bw', label: 'Manga B&W', fragment: 'monochrome, manga, greyscale' },
      { id: 'lineart', label: 'Lineart', fragment: 'lineart, sketch' },
      { id: 'semi-realistic', label: 'Semi-realistic', fragment: 'realistic, semi-realistic' },
      { id: 'ghibli-like', label: 'Ghibli-like', fragment: 'ghibli_inspired, soft_shading' },
      { id: 'visual-novel', label: 'Visual novel', fragment: 'game_cg, visual_novel' },
      { id: 'light-novel', label: 'Light novel', fragment: 'official_art, illustration' },
      { id: 'pixel-art', label: 'Pixel art', fragment: 'pixel_art' },
      { id: 'ink-wash', label: 'Ink wash', fragment: 'ink_(medium), sumi-e' },
      { id: 'vibrant-digital', label: 'Digital paint', fragment: 'vibrant, digital_media' },
      { id: 'flat-color', label: 'Flat color', fragment: 'flat_color, minimalism' },
      { id: 'retro-mecha', label: 'Retro mecha', fragment: 'retro_artstyle, mecha' },
      { id: 'dark-fantasy-art', label: 'Dark fantasy', fragment: 'dark_fantasy, gothic' },
      { id: 'pastel-soft', label: 'Soft pastel', fragment: 'pastel_colors, soft_shading' },
    ]},
    { id: 'mood', label: 'Mood', options: [
      { id: 'epic', label: 'Epic', fragment: 'epic, dramatic' },
      { id: 'slice', label: 'Slice of life', fragment: 'slice_of_life' },
      { id: 'melancholy', label: 'Melancholic', fragment: 'melancholy, lonely' },
      { id: 'whimsical', label: 'Whimsical', fragment: 'whimsical, cute' },
      { id: 'romantic', label: 'Romantic', fragment: 'romantic' },
      { id: 'dark-fantasy', label: 'Dark fantasy', fragment: 'dark, fantasy' },
      { id: 'heroic', label: 'Heroic', fragment: 'heroic, dramatic_angle' },
      { id: 'dreamy', label: 'Dreamy', fragment: 'dreamy, soft' },
      { id: 'tense', label: 'Tense', fragment: 'tense, suspense' },
      { id: 'comedic', label: 'Comedic', fragment: 'comedy, funny' },
      { id: 'mysterious', label: 'Mysterious', fragment: 'mysterious, mystery' },
      { id: 'wholesome', label: 'Wholesome', fragment: 'wholesome, heartwarming' },
      { id: 'tragic', label: 'Tragic', fragment: 'tragic, sad' },
      { id: 'energetic', label: 'Energetic', fragment: 'energetic, dynamic' },
      { id: 'serene', label: 'Serene', fragment: 'serene, peaceful' },
      { id: 'ominous', label: 'Ominous', fragment: 'ominous, dark' },
      { id: 'nostalgic', label: 'Nostalgic', fragment: 'nostalgic' },
      { id: 'triumphant', label: 'Triumphant', fragment: 'triumphant, victory' },
      { id: 'cozy', label: 'Cozy', fragment: 'cozy, warm' },
      { id: 'sensual', label: 'Sensual', fragment: 'seductive, sensual' },
      { id: 'adventurous', label: 'Adventurous', fragment: 'adventure' },
    ]},
    { id: 'quality', label: 'Quality boosters', options: [
      { id: 'bg', label: 'Detailed background', fragment: 'detailed_background, scenery' },
      { id: 'cel', label: 'Cel shading', fragment: 'cel_shading' },
      { id: 'anime-master', label: 'Masterpiece', fragment: 'masterpiece, best_quality' },
      { id: 'detailed-eyes', label: 'Detailed eyes', fragment: 'detailed_eyes, beautiful_detailed_eyes' },
      { id: 'intricate', label: 'Intricate detail', fragment: 'intricate_details, highres' },
      { id: 'dynamic-comp', label: 'Dynamic composition', fragment: 'dynamic_angle, dramatic' },
      { id: 'studio-anime', label: 'Studio key visual', fragment: 'official_art, key_visual' },
      { id: 'vibrant-render', label: 'Clean render', fragment: 'vibrant, highres' },
      { id: '8k', label: '8K illustration', fragment: 'absurdres, 8k' },
      { id: 'sharp-lineart', label: 'Sharp lineart', fragment: 'clean_lineart, sharp' },
      { id: 'high-detail', label: 'High detail', fragment: 'highly_detailed, intricate' },
      { id: 'vibrant-colors', label: 'Vibrant colors', fragment: 'vibrant_colors, saturated' },
      { id: 'smooth-shading', label: 'Smooth shading', fragment: 'smooth_shading, polished' },
      { id: 'dramatic-lighting', label: 'Dramatic lighting', fragment: 'dramatic_lighting, cinematic_lighting' },
      { id: 'best-quality', label: 'Best quality', fragment: 'best_quality, masterpiece' },
      { id: 'trending', label: 'Trending pixiv', fragment: 'trending_on_pixiv' },
      { id: 'official-art', label: 'Official art', fragment: 'official_art' },
      { id: 'crisp-render', label: 'Crisp render', fragment: 'crisp, clean' },
      { id: 'detailed-bg2', label: 'Detailed scenery', fragment: 'detailed_background, amazing_background' },
      { id: 'expressive', label: 'Expressive lines', fragment: 'expressive, dynamic_lines' },
      { id: 'polished', label: 'Polished finish', fragment: 'polished, high_quality' },
    ]},
  ],
}

/**
 * Pick one random option from every category for the given mode, returning a
 * `selected` map ready for assemblePrompt. `rng` is injectable for testing
 * (defaults to Math.random); it must return a value in [0, 1).
 */
export function randomSelection(
  mode: PromptMode,
  rng: () => number = Math.random,
): Record<string, string[]> {
  const selected: Record<string, string[]> = {}
  for (const cat of TEMPLATES[mode]) {
    if (cat.options.length === 0) continue
    const idx = Math.min(cat.options.length - 1, Math.floor(rng() * cat.options.length))
    selected[cat.id] = [cat.options[idx].id]
  }
  return selected
}

/** Join the selected fragments in fixed category order; dedupe; drop empties; comma-join. */
export function assemblePrompt(mode: PromptMode, selected: Record<string, string[]>): string {
  const fragments: string[] = []
  for (const catId of CATEGORY_ORDER) {
    const cat = TEMPLATES[mode].find((c) => c.id === catId)
    if (!cat) continue
    const chosen = selected[catId] ?? []
    for (const optId of chosen) {
      const opt = cat.options.find((o) => o.id === optId)
      if (opt && opt.fragment && !fragments.includes(opt.fragment)) fragments.push(opt.fragment)
    }
  }
  return fragments.join(', ')
}
