"""Print the launch tuning ComfyUI should start with, decided from this box's
hardware. Two modes, because the two answers have different shapes:

    python installer/reserve-vram.py                  -> --reserve-vram GB, or empty
    python installer/reserve-vram.py --tuning-flags   -> extra flags, or empty

Why this is a tracked file and not baked into the launcher: start-comfyui.* is
generated by the installer and gitignored (.gitignore:27), so a table written
into it would never reach an existing install via `git pull`. Keeping the table
here means tuning changes actually ship. One file covers both OSes and both
GPU vendors, so a threshold is never written twice in two shell languages.

stdout is the value alone (no trailing newline, callers interpolate it straight
into an arg list) or empty; warnings go to stderr.
"""
import os
import sys

# GB to hold back, by total VRAM. Thresholds sit BELOW nominal card sizes on
# purpose: a "32 GB" card reports 31.8 GiB and a "24 GB" card ~23.6 GiB, so
# comparing against 32 or 24 would never match. ComfyUI itself uses the same
# trick (`total_vram > 15 * 1024` for its 16 GB+ case).
#
# Only the 30+ row is MEASURED: A/B 2026-07-18 on a 32 GB RTX 5090 with the LTX
# video upscale pass, 78 -> 68 s/it and peak shared GPU memory 24 -> 16.5 GB.
# The 22 and 15 rows are reasoned down from it, not measured. Tune via
# RACCOON_RESERVE_VRAM and update this table when real numbers land.
#
# Below 15 GiB we reserve NOTHING on purpose. ComfyUI's own default is 600 MB
# (comfy/model_management.py:789); holding back whole gigabytes on a 12 GB card
# starves the model rather than protecting it. The app's low-VRAM (~1 MP) render
# mode is the correct lever at that tier.
_TIERS = ((30, 8), (22, 4), (15, 1))


def reserve_gb(total_gib):
    """GB to reserve for a card of `total_gib`, or None to use ComfyUI's default."""
    for floor, gb in _TIERS:
        if total_gib >= floor:
            return gb
    return None


# ── system RAM tier ───────────────────────────────────────────────────────────
# ComfyUI locks host memory into non-pageable pages so weights can DMA to the
# card, capped at 40% of system RAM on Windows and 90% on Linux, for NVIDIA and
# AMD alike (comfy/model_management.py:1489-1496, logged at startup as "Enabled
# pinned memory N"). The cap is filled lazily per tensor, not allocated up front,
# so the cost is not the whole 40% - it is that whatever DOES get pinned (model
# sized: ~6-7 GB for SDXL + its CLIP) is memory the OS can never reclaim, no
# matter what else on the box needs it.
#
# On a 64 GB box that is headroom well spent. On a 32 GB box it is most of what
# the user has. Field report 2026-07-27 (32 GB / RX 9070 XT, SDXL + hires fix):
# RAM pegged at ~99% with generation itself healthy - every model logged
# "full load: True", no OOM, no lowvram patches anywhere in the session.
#
# Trade-off: unpinned host memory cannot DMA, so host<->device copies fall back
# to a staged path. That costs model load and offload time, not sampling time.
# Worth it only where the pinning is doing more harm than good, hence the tier.
#
# Threshold sits above nominal for the same reason the VRAM tiers sit below it:
# a "32 GB" box reports ~31.7 GiB, a "48 GB" one ~47.7 GiB. So 33 keeps pinning
# on 48 GB and up, and drops it at 32 GB and below.
_PIN_MIN_RAM_GIB = 33


def pinned_memory_flags(total_gib):
    """Extra ComfyUI args for a box with `total_gib` of RAM.

    Unknown RAM keeps ComfyUI's default: this tier trades transfer speed for
    reclaimable memory, and that is a bad trade to make on a box we could not
    measure.
    """
    if total_gib is None or total_gib >= _PIN_MIN_RAM_GIB:
        return []
    return ['--disable-pinned-memory']


# ── live-preview size tier ────────────────────────────────────────────────────
# The studio canvas shows the image building up because ComfyUI TAESD-decodes a
# preview every sampling step. That decode is real GPU work on every step, and it
# scales with area: our 768 preview is 2.25x the pixels of ComfyUI's own 512
# default. On a big card that is free and the bigger preview looks better; on a
# small one it competes with the sampler for exactly the VRAM the sampler is
# already short of.
#
# So 768 is a treat for cards that can afford it, not a baseline. Below the
# threshold we emit nothing and let ComfyUI use its own 512 - deliberately not a
# number of our own invention, since we have measured neither.
_PREVIEW_MIN_VRAM_GIB = 15  # a "16 GB" card reports ~15.7 GiB
_PREVIEW_SIZE_LARGE = '768'


def preview_flags(total_gib):
    """Preview-size args for a card of `total_gib`, or [] for ComfyUI's default."""
    if total_gib is None or total_gib < _PREVIEW_MIN_VRAM_GIB:
        return []
    return ['--preview-size', _PREVIEW_SIZE_LARGE]


def parse_override(raw):
    """RACCOON_RESERVE_VRAM -> GB, or None for 'use ComfyUI's default' (0 or blank).

    Raises ValueError when the value isn't a number, so main() can fall back to
    the tier table. Swallowing it here would silently drop the tuning: a typo'd
    var would leave a 32 GB card on ComfyUI's 600 MB default and reintroduce the
    shared-memory spill the 8 GB reserve was measured to prevent.
    """
    if raw is None or raw.strip() == '':
        return None
    value = float(raw)
    return None if value <= 0 else value


def total_vram_gib():
    """Total VRAM of the first GPU, or None if there isn't a usable one.

    torch.cuda covers AMD too: PyTorch-ROCm aliases HIP into the cuda namespace,
    so this is one code path for both vendors. Costs ~1.5 s (the torch import),
    which is small next to ComfyUI's own startup.
    """
    import torch
    if not torch.cuda.is_available():
        return None
    return torch.cuda.get_device_properties(0).total_memory / (1024 ** 3)


def parse_pin_override(raw):
    """RACCOON_PINNED_MEMORY -> True (keep pinning), False (disable), None (use the tier).

    Numeric like its RACCOON_RESERVE_VRAM sibling, and raising on anything else
    for the same reason: a typo must fall back to the tier rather than silently
    decide a memory policy, and 'off' reading as truthy would do exactly that.
    """
    if raw is None or raw.strip() == '':
        return None
    return float(raw) != 0


def total_ram_gib():
    """Total physical RAM, or None if it can't be determined.

    psutil is a hard ComfyUI dependency (its own pin budget calls it), and this
    always runs under the ComfyUI venv, so this adds nothing to install. Unlike
    total_vram_gib() it needs no torch import, so the RAM half of --tuning-flags
    costs ~50 ms rather than a second 1.5 s torch load.
    """
    try:
        import psutil
        return psutil.virtual_memory().total / (1024 ** 3)
    except Exception as exc:
        sys.stderr.write('reserve-vram: could not probe RAM (%s)\n' % exc)
        return None


def resolve_reserve_gb(total_gib):
    """GB to reserve given an already-probed VRAM total, honouring the override.

    Split out from main() so --tuning-flags can reuse it against the SAME probe
    it already does for the preview tier. Two modes each importing torch cost the
    launcher a measured ~1.3 s of pure duplicate work.
    """
    raw = os.environ.get('RACCOON_RESERVE_VRAM')
    if raw is not None and raw.strip() != '':
        try:
            return parse_override(raw)
        except ValueError:
            sys.stderr.write(
                'RACCOON_RESERVE_VRAM=%r is not a number - using the VRAM tier instead\n' % raw)
    return None if total_gib is None else reserve_gb(total_gib)


def tuning_main():
    """--tuning-flags: every hardware-derived launch flag, ONE PER LINE.

    One per line, not space separated: callers then split on newlines, and a flag
    whose value ever contains a space (a path, say) cannot silently shatter into
    two arguments.
    """
    raw = os.environ.get('RACCOON_PINNED_MEMORY')
    try:
        keep = parse_pin_override(raw)
    except ValueError:
        sys.stderr.write(
            'RACCOON_PINNED_MEMORY=%r is not a number - using the RAM tier instead\n' % raw)
        keep = None
    if keep is None:
        flags = pinned_memory_flags(total_ram_gib())
    else:
        flags = [] if keep else ['--disable-pinned-memory']

    # One VRAM probe feeds both the reserve tier and the preview tier. Best
    # effort: a driver problem here must not cost the box its RAM tuning, which
    # is the flag that actually rescues a session.
    total = None
    try:
        total = total_vram_gib()
    except Exception as exc:
        sys.stderr.write('reserve-vram: could not probe VRAM (%s)\n' % exc)
    gb = resolve_reserve_gb(total)
    if gb:
        flags += ['--reserve-vram', '%g' % gb]
    flags += preview_flags(total)

    # Force LF. On Windows, text-mode stdout translates \n to \r\n, and the shell
    # reader then hands ComfyUI "--reserve-vram\r" — an unrecognised argument that
    # kills the launch. Caught by `cat -A` on the real output, not by reasoning.
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(newline='\n')
    sys.stdout.write('\n'.join(flags))
    return 0


def main():
    """Bare mode: just the reserve GB. Kept for the installers' summary line —
    the launcher gets this via --tuning-flags instead, in one process."""
    total = None
    try:
        total = total_vram_gib()
    except Exception as exc:  # no torch, no driver, CPU-only box
        sys.stderr.write('reserve-vram: could not probe VRAM (%s)\n' % exc)
    gb = resolve_reserve_gb(total)
    if gb:
        # No trailing newline: callers interpolate this straight into an arg list.
        sys.stdout.write('%g' % gb)
    return 0


def _self_check():
    assert reserve_gb(31.8) == 8, 'a 32 GB card reports ~31.8 GiB'
    assert reserve_gb(23.6) == 4, 'a 24 GB card reports ~23.6 GiB'
    assert reserve_gb(15.7) == 1, 'a 16 GB card reports ~15.7 GiB'
    assert reserve_gb(11.6) is None, '12 GB tier uses ComfyUI default'
    assert reserve_gb(7.8) is None, '8 GB tier uses ComfyUI default'
    # Boundaries land on the documented tier, not the one above it.
    assert reserve_gb(30) == 8 and reserve_gb(29.9) == 4
    assert reserve_gb(22) == 4 and reserve_gb(21.9) == 1
    assert reserve_gb(15) == 1 and reserve_gb(14.9) is None
    # Overrides
    assert parse_override('6') == 6
    assert parse_override('0') is None, '0 means "let ComfyUI decide"'
    assert parse_override('') is None and parse_override(None) is None
    assert parse_override('  2.5 ') == 2.5
    assert parse_override('-4') is None
    # A typo must surface as ValueError so main() falls back to the tier table.
    # Returning None here would silently drop the tuning to ComfyUI's default.
    for bad in ('banana', '4GB', '--'):
        try:
            parse_override(bad)
        except ValueError:
            pass
        else:
            raise AssertionError('parse_override(%r) should raise ValueError' % bad)
    # RAM tier: pinning stays on where there is RAM to spare, off where there
    # isn't. The 31.7/47.7 pair is the whole point of the threshold sitting
    # above nominal - a "32 GB" box must land on the disable side.
    assert pinned_memory_flags(31.7) == ['--disable-pinned-memory'], '"32 GB" box reports ~31.7 GiB'
    assert pinned_memory_flags(15.8) == ['--disable-pinned-memory'], '16 GB box, the worst case'
    assert pinned_memory_flags(47.7) == [], '"48 GB" box reports ~47.7 GiB and keeps pinning'
    assert pinned_memory_flags(63.7) == [], '64 GB box keeps pinning'
    assert pinned_memory_flags(33) == [] and pinned_memory_flags(32.9) == ['--disable-pinned-memory']
    # Unmeasurable RAM must not silently cost every such box its DMA transfers.
    assert pinned_memory_flags(None) == [], 'unknown RAM uses ComfyUI default'
    # Pin override
    assert parse_pin_override('1') is True and parse_pin_override('0') is False
    assert parse_pin_override('') is None and parse_pin_override(None) is None
    assert parse_pin_override('  0 ') is False, 'whitespace must not read as "unset"'
    # Preview tier: the big preview is for cards that can spare the per-step decode.
    assert preview_flags(15.7) == ['--preview-size', '768'], '"16 GB" card reports ~15.7 GiB'
    assert preview_flags(31.8) == ['--preview-size', '768'], 'a 32 GB card keeps the big preview'
    assert preview_flags(11.6) == [], '12 GB card falls back to ComfyUI default'
    assert preview_flags(7.8) == [], '8 GB card falls back to ComfyUI default'
    assert preview_flags(15) == ['--preview-size', '768'] and preview_flags(14.9) == []
    assert preview_flags(None) == [], 'unknown VRAM uses ComfyUI default'
    # resolve_reserve_gb: the tier, and the override that beats it. Env is
    # restored after each case so the checks cannot leak into one another.
    _saved = os.environ.pop('RACCOON_RESERVE_VRAM', None)
    try:
        assert resolve_reserve_gb(31.8) == 8 and resolve_reserve_gb(15.7) == 1
        assert resolve_reserve_gb(11.6) is None, '12 GB tier uses ComfyUI default'
        assert resolve_reserve_gb(None) is None, 'unprobeable card adds no flag'
        os.environ['RACCOON_RESERVE_VRAM'] = '2'
        assert resolve_reserve_gb(31.8) == 2, 'a valid override beats the tier'
        assert resolve_reserve_gb(None) == 2, 'and applies even when probing failed'
        os.environ['RACCOON_RESERVE_VRAM'] = '0'
        assert resolve_reserve_gb(31.8) is None, '0 means "let ComfyUI decide"'
        os.environ['RACCOON_RESERVE_VRAM'] = 'banana'
        assert resolve_reserve_gb(31.8) == 8, 'a typo falls back to the tier, not to nothing'
    finally:
        os.environ.pop('RACCOON_RESERVE_VRAM', None)
        if _saved is not None:
            os.environ['RACCOON_RESERVE_VRAM'] = _saved
    for bad in ('banana', 'off', 'true'):
        try:
            parse_pin_override(bad)
        except ValueError:
            pass
        else:
            raise AssertionError('parse_pin_override(%r) should raise ValueError' % bad)
    print('reserve-vram OK')


if __name__ == '__main__':
    if '--self-check' in sys.argv:
        _self_check()
    elif '--tuning-flags' in sys.argv:
        sys.exit(tuning_main())
    else:
        sys.exit(main())
