"""Print the --reserve-vram value (in GB) ComfyUI should launch with, or print
nothing when ComfyUI's own default is the better choice.

Why this is a tracked file and not baked into the launcher: start-comfyui.* is
generated by the installer and gitignored (.gitignore:27), so a table written
into it would never reach an existing install via `git pull`. Keeping the table
here means tuning changes actually ship. One file covers both OSes and both
GPU vendors.

Usage (stdout is the number alone, or empty; warnings go to stderr):
    python installer/reserve-vram.py
"""
import os
import sys

# GB to hold back, by total VRAM. Thresholds sit BELOW nominal card sizes on
# purpose: a "32 GB" card reports 31.8 GiB and a "24 GB" card ~23.6 GiB, so
# comparing against 32 or 24 would never match. ComfyUI itself uses the same
# trick (`total_vram > 15 * 1024` for its 16 GB+ case).
#
# Only the 30+ row is MEASURED: A/B 2026-07-18 on a 32 GB RTX 5090 with the LTX
# video upscale pass, 78 -> 68 s/it and peak shared GPU memory 24 -> 16.5 GB.
# The 22 and 15 rows are reasoned down from it, not measured. Tune via
# RACCOON_RESERVE_VRAM and update this table when real numbers land.
#
# Below 15 GiB we reserve NOTHING on purpose. ComfyUI's own default is 600 MB
# (comfy/model_management.py:789); holding back whole gigabytes on a 12 GB card
# starves the model rather than protecting it. The app's low-VRAM (~1 MP) render
# mode is the correct lever at that tier.
_TIERS = ((30, 8), (22, 4), (15, 1))


def reserve_gb(total_gib):
    """GB to reserve for a card of `total_gib`, or None to use ComfyUI's default."""
    for floor, gb in _TIERS:
        if total_gib >= floor:
            return gb
    return None


def parse_override(raw):
    """RACCOON_RESERVE_VRAM -> GB, or None for 'use ComfyUI's default' (0 or blank).

    Raises ValueError when the value isn't a number, so main() can fall back to
    the tier table. Swallowing it here would silently drop the tuning: a typo'd
    var would leave a 32 GB card on ComfyUI's 600 MB default and reintroduce the
    shared-memory spill the 8 GB reserve was measured to prevent.
    """
    if raw is None or raw.strip() == '':
        return None
    value = float(raw)
    return None if value <= 0 else value


def total_vram_gib():
    """Total VRAM of the first GPU, or None if there isn't a usable one.

    torch.cuda covers AMD too: PyTorch-ROCm aliases HIP into the cuda namespace,
    so this is one code path for both vendors. Costs ~1.5 s (the torch import),
    which is small next to ComfyUI's own startup.
    """
    import torch
    if not torch.cuda.is_available():
        return None
    return torch.cuda.get_device_properties(0).total_memory / (1024 ** 3)


def main():
    raw = os.environ.get('RACCOON_RESERVE_VRAM')
    if raw is not None and raw.strip() != '':
        try:
            # A valid override wins outright, including "0" meaning "no flag".
            gb = parse_override(raw)
            if gb:
                sys.stdout.write('%g' % gb)
            return 0
        except ValueError:
            sys.stderr.write(
                'RACCOON_RESERVE_VRAM=%r is not a number - using the VRAM tier instead\n' % raw)
            # fall through to the tier table rather than dropping the tuning
    try:
        total = total_vram_gib()
    except Exception as exc:  # no torch, no driver, CPU-only box
        sys.stderr.write('reserve-vram: could not probe VRAM (%s)\n' % exc)
        return 0
    gb = None if total is None else reserve_gb(total)
    if gb:
        # No trailing newline: callers interpolate this straight into an arg list.
        sys.stdout.write('%g' % gb)
    return 0


def _self_check():
    assert reserve_gb(31.8) == 8, 'a 32 GB card reports ~31.8 GiB'
    assert reserve_gb(23.6) == 4, 'a 24 GB card reports ~23.6 GiB'
    assert reserve_gb(15.7) == 1, 'a 16 GB card reports ~15.7 GiB'
    assert reserve_gb(11.6) is None, '12 GB tier uses ComfyUI default'
    assert reserve_gb(7.8) is None, '8 GB tier uses ComfyUI default'
    # Boundaries land on the documented tier, not the one above it.
    assert reserve_gb(30) == 8 and reserve_gb(29.9) == 4
    assert reserve_gb(22) == 4 and reserve_gb(21.9) == 1
    assert reserve_gb(15) == 1 and reserve_gb(14.9) is None
    # Overrides
    assert parse_override('6') == 6
    assert parse_override('0') is None, '0 means "let ComfyUI decide"'
    assert parse_override('') is None and parse_override(None) is None
    assert parse_override('  2.5 ') == 2.5
    assert parse_override('-4') is None
    # A typo must surface as ValueError so main() falls back to the tier table.
    # Returning None here would silently drop the tuning to ComfyUI's default.
    for bad in ('banana', '4GB', '--'):
        try:
            parse_override(bad)
        except ValueError:
            pass
        else:
            raise AssertionError('parse_override(%r) should raise ValueError' % bad)
    print('reserve-vram OK')


if __name__ == '__main__':
    if '--self-check' in sys.argv:
        _self_check()
    else:
        sys.exit(main())
